fix #483
autokey-py3/autokey-py3 pull request #486
Opened 2020-11-30 00:55 UTC by fx-kirin

https://github.com/autokey/autokey/issues/483

Reopening https://github.com/autokey/autokey/pull/484

2020-11-30 15:05 UTC, sebastiansam55 requested changes
When you open a PR try to include more information in the description than fix x, even a short description is better than nothing, our only active person with git PR approval is not a python expert so do your best to explain what your PR is changing and how, the more information the better. 

This PR is also still on `master` instead of `develop`, when you go to the PR page at the top there are a few dropdowns, make sure you select the right branch for both your fork and for the main autokey fork. I also try to name forks prefixed with what branch it is based on so it is more clear (my fork in the screen shot is `develop_altgr` instead of `altgr`, so it is clear to the approver that the PR is for the develop branch based on the develop branch).

![Screenshot from 2020-11-30 09-59-49](https://user-images.githubusercontent.com/1707320/100625671-d0b61380-32f2-11eb-91cc-f55bdb03c2a0.png)
Note the 2nd dropdown from the left is on develop, by default github sets it to `master` so you have to change it to `develop` everytime.

Sorry to be so nitpicky! 😬😬😬

2020-11-30 15:05 UTC, sebastiansam55 commented on lib/autokey/scripting.py
> +                if len(output) > 0:
At first glance I had questions about if an error would still occur if the command called had no output but it should be good, it seems that with the addition of `stdout=subprocess.PIPE,` the "output" of a command with no other output (eg a test script like `#!/bin/sh`) will still be a empty string `''`.

Unrelated but is there any reason why we don't swap from
`output[:-1]`
to
`.rstrip()`?

2020-12-01 00:08 UTC, fx-kirin commented
Thank you for your reviewing. l just wanted to fix a bug for me and I don't have time to go further detail of this change including last one  which causes this bug. You can close this issue and PR if you want and I don't know which implementation is better. https://github.com/autokey/autokey/issues/354

2020-12-03 06:41 UTC, josephj11 requested changes

2020-12-03 06:41 UTC, josephj11 commented on lib/autokey/scripting.py
> +                if len(output) > 0:
I don't know Python, but rstrip seems more expressive/clear than indexing the last character in the string.

2020-12-03 06:41 UTC, josephj11 commented on lib/autokey/scripting.py
> +                if len(output) > 0:
Did someone finally copy my Problem Reporting Guide from the autokey-python2 branch to the master? I don't see it. That's why the link points to the old repo.

2020-12-03 06:41 UTC, josephj11 commented on lib/autokey/scripting.py
> +                if len(output) > 0:
The version should probably be 0.95.11 or 0.96 - depending on whether someone wants to put out a minor release before 0.96. I don't think the date of a released version should be modified.

2021-03-10 19:39 UTC, josephj11 commented
See also #462.

2021-04-26 04:45 UTC, BlueDrink9 commented
Closed by #489

2021-04-26 04:45 UTC, closed without merging