Fix #483
autokey-py3/autokey-py3 pull request #489
Opened 2020-12-02 20:49 UTC by sebastiansam55

Also swaps from striping trailing new line using indexes to `rstrip('\n')`.

See https://github.com/autokey/autokey/pull/486/files#r532656403.

Output of `subprocess` seems to always be at least a empty string: `''`, so checking length shouldn't be a problem, no more than the previous method, `endswith` which also (I think) assumes output to be a string.

Credit goes to https://github.com/fx-kirin for original fix.

2020-12-29 15:08 UTC, mvindiola1 commented
I ran into this error today. I wanted to add two comments that you might consider.

1. You do not really need the conditional because if you rstrip an empty string you get the empty string back. You could do it cleanly and more expressively in one line like this:
    `output = p.communicate()[0].rstrip('\n')`.

    As an aside, if you want to use python indexing, the correct way to test this would have been:
    `if t[-1:] == "\n":`

2. There are a couple other places where you could do the same thing if you wanted consistency :
https://github.com/autokey/autokey/blob/c2ebcbba75ce40ed080c78216730b93690cb9a21/lib/autokey/scripting/dialog_gtk.py#L42
https://github.com/autokey/autokey/blob/c2ebcbba75ce40ed080c78216730b93690cb9a21/lib/autokey/scripting/dialog_qt.py#L42
https://github.com/autokey/autokey/blob/c2ebcbba75ce40ed080c78216730b93690cb9a21/lib/autokey/scripting/window.py#L244

2020-12-30 23:28 UTC, BlueDrink9 requested changes

2020-12-30 23:28 UTC, BlueDrink9 commented on lib/autokey/scripting/system.py
> +                if len(output) > 0:
Good advice @mvindiola1. @sebastiansam55 if you just remove this conditional, then @josephj11 should merge this change.

As an aside, I couldn't replicate this issue with automated tests, so if you can figure out how to, add the test to `autokey/tests/scripting_api/test_system.py`

2021-03-11 02:43 UTC, BlueDrink9 commented on lib/autokey/scripting/system.py
> +                if len(output) > 0:
@sebastiansam55 can you quickly please replace lines 46-49 with

```python
# Most shell output has a new line at the end, which we don't want.
output = output.rstrip("\n")
```

Then repush and we can merge. This has cropped up as a bug elsewhere.

2021-03-12 03:52 UTC, BlueDrink9 commented
@josephj11 Should be good to merge

2021-03-12 19:18 UTC, merged