Fix develop branch to run under X11 and on Fedora
autokey-py3/autokey-py3 pull request #992
Opened 2024-12-16 17:28 UTC by dlk3

Here are the changes I made to get the "develop" branch of AutoKey working under both X11 and Wayland on my Fedora workstation.  I have tested this version on Ubuntu 24.04, Fedora 40, and Fedora 41 under both Wayland and X11.  The list of changes I made is in the [CHANGELOG.rst](https://github.com/dlk3/autokey/blob/wayland/CHANGELOG.rst) file.  I have heavily edited the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) file to document the installation process.

2024-12-17 08:30 UTC, josephj11 commented
Outstanding! Hopefully, we can get some testers to try it out. I flagged the possibe reviewers.

After we get any timely feeback from them, we can announce it to the community and interested users can use the zero install method to test it without affecting their production installs.

2024-12-17 16:26 UTC, dlk3 commented
> What doesn't work? Are the window API calls implemented?

The window API calls seem to work.  I tested a script that uses it.  So far I haven't found anything that doesn't work, but I don't use the more advanced features, like mouse automation for example.

The visgrep and png2pat tools from xautomation are still called out as optional prereqs when AutoKey starts, if they aren't installed, but I've never used them so I have no test cases for them.

2024-12-17 21:16 UTC, Elliria commented
This is going to take some time to examine. Meanwhile, I'm curious if you started with the code-base before @sebastiansam55's Wayland code was added to AutoKey and if this is in addition to that or if this is a separate implementation of Wayland code? We've got at least three Wayland submissions at this point and I'm not clear on which is what or what is which.

2024-12-17 21:56 UTC, dlk3 commented
@Elliria:
This PR contains fixes I made to get Sam's code working.  This is not a new solution.

2024-12-18 10:05 UTC, josephj11 commented
@Elliria based on @BlueDrink9 's analysis of the first PR (after @sebastiansam55 's), was that it was garbage. The next one was suspect because it changed too much ad we recieved no communication from the OP. I'm going t close it sometime if we don't hear from the author.

So @dlk3 's PRs built on top of @sebastiansam55 's are  the only live candidate ATM.

Since it's against develop and not main, the criteria  for merging is  a bit more flexible. I would like it  to have your blessing (in as far as you are able to analyse/test it). It would be great if one of our other contributing devs would weigh in as well.

If we get it into develop, then people can easily zero install test it for the real proof of whether it works or not.

2024-12-18 10:33 UTC, josephj11 reviewed
Comments:

Why are icons in .gitignore? Just want to understand.

I asked the devs a while ago when they were still active and they thought AutoKey still needed a lot of work before it was ready for 1.0. I'd like to see 0.97.0 first. And  maybe a 0.96.1  before that to make sure we get the release process right and get Debian off of 0.95.10 (because 0.96.0 had test failures that scared them off).

I'm sure @Elliria will chime in here, but what happened to Python 3.9 as a minimum? AFAIK, that should still be viablle unless  there's a good reason for Autokey to require 3.10 and above.

2024-12-18 15:34 UTC, dlk3 commented
> Why are icons in .gitignore? Just want to understand.
That specific directory is created when the build process is run.  It is not part of the source code and does not (in my opinion) need to be pushed into github.  It and the "build " directory were the reason that there were 147 files in @promisingcoder's PR request (#990).
> I asked the devs a while ago when they were still active and they thought AutoKey still needed a lot of work before it was ready for 1.0. I'd like to see 0.97.0 first. And maybe a 0.96.1 before that to make sure we get the release process right and get Debian off of 0.95.10 (because 0.96.0 had test failures that scared them off).
Ok, any new version number is fine with me.  You guys tell me what to use, or change it to whatever you want when you pull in my PR.  I assumed that semantic versioning was the strategy in use.  I wanted to indicate that this is a major release, given the massive change to the code that "develop" represents versus 0.96.0.  In semantic versioning using something like 0.96.1 instead would indicate that this is a minor patch update, just some trivial bug fix, and that definitely isn't what this is.
> I'm sure @Elliria will chime in here, but what happened to Python 3.9 as a minimum? AFAIK, that should still be viablle unless there's a good reason for Autokey to require 3.10 and above.
Any version you want is fine with me. I have not investigated the minimum version that will run Sam's code.

2024-12-18 23:32 UTC, josephj11 commented
@dlk3 Yes, we do use semantic versioning. What I meant, but didn't spell out, was that it might be useful to put out a maintenance release, 0.96.1 to fix things like Python versions in tests and #600 first. That's a less dangerous way to make sure our release process works and that Debian can upgrade from our really old 0.95.10 release.

The Wayland changes would definitely be 0.97.0 (or 1.0, if there's sufficient support for that).

2024-12-19 21:55 UTC, Elliria commented
I'm on this, guys. I'm part of the way through it and have several files tagged as viewed and a file full of comments and questions, but a girl's gotta eat. GitHub will remember where I was when I log in again, though.

2024-12-20 01:14 UTC, josephj11 approved these changes
@Elliria LGTM. Any reason not to merge this now?

2024-12-20 04:24 UTC, Elliria requested changes
<mark>OMG, you're amazing! Can we keep you? You're very thorough in your comments and documentation and you're worlds ahead of me in coding ability.</mark>

Please forgive any stupid questions or seemingly ignorant comments. I'm still learning, but figured I'd give this my best. Without further ado:

* **.gitignore**: LGTM

* **CHANGELOG.rst**:
   * I would leave out the comment on line 8 and use it in the commit message instead.
   * You'll want to mention [issue #961](https://github.com/autokey/autokey/issues/961) in the changelog and commits when you do the [puremagic](https://pypi.org/project/puremagic/) fix in the various files since that's the issue that was going to be solved by **imagesize** (which isn't one of the alternatives GitHub suggested).
   * I like your use of imperial mood in the first few statements and would recommend continuing that all throughout.

* **apt-requirements.txt**: LGTM

* **autokey-gnome-extension/44/extension.js**: This is beyond me, but is there any concern over the use of a different version of the GPL?

* **autokey-gnome-extension/44/metadata.json**: LGTM, but is there any concern over using ickyicky's code with a different version of the GPL?

* **autokey-gnome-extension/46/extension.js**: This is beyond me, but is there any concern over the use of a different version of the GPL?

* **autokey-gnome-extension/46/metadata.json**: LGTM, but is there any concern over using ickyicky's code with a different version of the GPL?

* **autokey-gnome-extension/Makefile**: This is beyond me.

* **autokey-gnome-extension/README.md**: LGTM - love it - we should create more of these.

* **lib/autokey/autokey_app.py**: accidental white-space got added in line 112. The regex is beyond me.

* **lib/autokey/common.py**: LGTM

* **lib/autokey/gnome_interface.py**: LGTM

* **lib/autokey/gtkapp.py**: LGTM

* **lib/autokey/gtkui/configwindow.py**: LGTM

* **lib/autokey/interface.py**: OMG, that regex is so very beyond me. I suspect it's a torture device used on misbehaving developers. <==<mark>[it's working]</mark> And in response to your comments in the addition of the missing `get_window_list` method, it doesn't show up in [a search of the AutoKey code](https://github.com/search?q=repo%3Aautokey%2Fautokey+get_window_list&type=code), but it would be interesting to figure out what problem(s) it could solve.

* **lib/autokey/iomediator/iomediator.py**: I can't figure out what changed on line 392, so it LGTM.

* **lib/autokey/model/abstract_abbreviation.py**: LGTM

* **lib/autokey/model/constants.py**: LGTM

* **lib/autokey/model/key.py**: LGTM

* **lib/autokey/scripting/highlevel.py**: LGTM

* **lib/autokey/uinput_interface.py**: LGTM

* **pip-requirements.txt**: LGTM

* **rpm-requirements.txt**: LGTM, but what's it for?

* **setup.cfg**: We'll add those after [PR #994](https://github.com/autokey/autokey/pull/994) goes through, but please also include **3.9** and **3.10**. Can we also get rid of the comment in lines 23 through 28 since this seems to solve its problem? Thank you for demonstrating the `pyasyncore` syntax, by the way. I wasn't able to figure out quite how to do that.

* **setup.py**:
  * Lines 36 and 37: That's taken care of with version **3, 9, 20** in [PR #994](https://github.com/autokey/autokey/pull/994).
  * Line 140 is taken care of with version **3.9** in line 132 of [PR #994](https://github.com/autokey/autokey/pull/994).
Line 194: Please do add the `puremagic` line to the file once [PR #994](https://github.com/autokey/autokey/pull/994) has gone through.
  * Line 213 is taken care of with version **3.9** on line 192 in  [PR #994](https://github.com/autokey/autokey/pull/994).

* **wayland_install.md**:
  * In lines 4 through 9, you mention several GNOME shell versions, but not the 45+ that was mentioned in the text that replaces. Did you find that it doesn't run on GNOME Shell 45+ or should that be added to the list? Note that it looks like version 45 is supported in `metadata.json`.
  * In lines 11 through 19, is there a reason why you and Sam both have us cloning your repositories to test Wayland? Would the [wiki instructions for cloning a pull request](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request) work for this so that we can keep the tests local?
  * I have no knowledge of Fedora, so will have to trust that you know the steps for that.
  * Line 55: "we" should probably be "you" since you've used "you" all throughout.
  * Line 64: You might want to replace "is not corrupted by" with "is not in conflict with" (just to be a bit gentler).
  * Line 92 through 99: Just curious why someone wouldn't already have the AutoKey icons if they've gotten AutoKey from us.
  * Lines 100 through 113: You might want to add one additional step for folks who made some sort of configuration change they'd like to keep (like adding a new script or something) that needs to be backed up first.

2024-12-20 04:34 UTC, Elliria commented
By the way, our friendly neighborhood contributor, @userdocs, shared [this](https://imgur.com/8KdK8bo) with me today and it seems to go nicely with this PR.

2024-12-20 04:35 UTC, Elliria commented
Thanks to both of you for sorting out the various Wayland contributions we've had lately.

2024-12-20 09:03 UTC, josephj11 commented
A few comments:

AutoKey is licensed under GPL 3+. IIUC, if we add anything to it, it can't be a lower level of GPL. (We can use other software with different licenses, if necessary.) If we are calling out to code with different licenses, that should be fine. If we  are copy pasting or including whole source files with  different licenses, that might require a legal opinion. IDK about such gray areas.

Wayland integration is  a major enhancement, not an incremental fix/patch. It requires at least 0.97.0.
0.96.1, if we ever release it, could do things like fix the build/tests, add #600, and other very small things. 
It might be a good idea to make Debian happy and make sure our release process works well before we go big.

I haven't looked into the window.list thing at all. It's not in the current API docs, so it's not exposed directly to users now.

What it would be good for:
Let's say I have three Vivaldi windows open and I need to switch to one of them. I could get a list of Vivaldi windows and do something in my script to examine each one until I find the one(s) I need. Some apps have pop-up dialogs that also appear as app windows, so those have to be dealt with as well. In x11, lots of things on the screen (and many that are invisible) are also treated as windows. Getting to the right one(s) can be tricky.

The regexes in interface.py don't look that bad, just long. I threw one into Venice.ai and it explained what it does bit by bit. Too long to include here. That's something the AIs are good at.

2024-12-20 14:30 UTC, Elliria commented
I don't know my way around the requirements of the GPL. The four files in question all use **SPDX-License-Identifier: GPL-2.0-or-later** and [AutoKey uses SPDX-License-Identifier: GPL-3.0-or-later](https://github.com/autokey/autokey/blob/master/LICENSE) and I'm not sure how it works when including code that uses different versions of the GPL into one program, so I'm asking and leaving it to **Those Who Know**.

The AutoKey version listed on the **develop** branch in [lib/autokey/common.py](https://github.com/autokey/autokey/blob/5940860b1d3e93beb1dbdeabdaba04a70ff7635f/lib/autokey/common.py#L38) is currently at **0.96.0-beta.9** and should have been at  **0.96.1-beta.0**. What a mess. The **0.96.0** part implies that it's a beta for **0.96.0**, which is already released [sigh]. Should we make that change before putting this PR through so that we have a natural progression of version numbers in the project's history or would it be better to just chalk that up to one of the many messes that are currently being cleaned up?

You're right that this is a major jump in functionality, so **1.0.0-beta.1** is perfect to signify that. I'm changing that file's comment to LGTM. Sorry for the noise on that one.

The window-list examples sound interesting and that's a nice future feature.

I'll leave the regexes to you guys. In my little world, they're a beautiful, mystical, and necessary evil that only gets dragged out from a deep, dark corner when nothing else will do and get used as quickly as possible and forgotten even more quickly. I'm glad you're on it.

2024-12-21 03:43 UTC, josephj11 commented
We should not have different GPL  versions within our code. IIRC, GPL 3 includes provsions to allow use with DRM software. A lot of purists don't like that (or didn't when it was new). If we include any essential new code based on GPL 2, one of two things probably happens. Either a class of people/applications that were previouslly allowed ro  use AutoKey can no longer legally use it or our whole license's validity gets called into question because the license is being used improperly.

I will not merge any code that is licensed under GPL2 into the body of AutoKey. I am not the only one with merge capabilities, so the result is not final, but,  if someone else does it, I will not be happy.

As a note: I woud have been happier if we were licensed under GPL2, but the way the licenses are written, there's no legal way to go back and  this branch chose GPL3, either before I got here or inherited it from the original branch. I don't feel like looking.

I'm not going to make  big deal about it, but I would still prefer that the next enhancement branch be 0.97.0. When this subject was last breached (by me), the two active developers were both against going to 1.0  because they felt the code and technicall debt didn't warrant it. Only a little of  that has been improved since then. I believe @BlueDrink9 was involved with this (and maybe Thomas Hess).

2024-12-21 08:41 UTC, dlk3 commented
@Elliria Here are my responses on your comments:

>     * **CHANGELOG.rst**:
What I wrote in the CHANGELOG is for our internal consumption during development.  When you actually go ahead and release this code (move it to "master"), then everything I've written in there should be reduced to one line: "Added support for the Wayland desktop environment"  That's my opinion anyway.

>     * **autokey-gnome-extension/44/extension.js**: This is beyond me, but is there any concern over the use of a different version of the GPL?
I paid no attention to the license statements in these files.  I learned long ago to always defer license questions to the lawyers.  My guess is that as long as they're all some form of open-source license there's no real issue.  Especially so if it's a question of GPLv2 vs GPLv3.

>     * **rpm-requirements.txt**: LGTM, but what's it for?
It lists the prerequisite packages that have to be installed on Fedora before AutoKey will run.  Nothing depends on this file, it's more along the lines of a set of notes.  I thought since there was an apt-requirements for Ubuntu/Debian, there ought to be a similar file for Fedora.
 
>     * **wayland_install.md**:
>       * In lines 4 through 9, you mention several GNOME shell versions, but not the 45+ that was mentioned in the text that replaces. Did you find that it doesn't run on GNOME Shell 45+ or should that be added to the list? Note that it looks like version 45 is supported in `metadata.json`.
The new "make" file I created handles all this version stuff.  It installs whichever version is appropriate automagically.

>       * In lines 11 through 19, is there a reason why you and Sam both have us cloning your repositories to test Wayland? Would the [wiki instructions for cloning a pull request](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request) work for this so that we can keep the tests local?
The reason in my case is that you have not yet pulled in my PR.  Anyone who wants to test my code right now has to get it from me.  There is a NOTE right in there that basically implies that this changes when you actually pull in my PR into your repo.

>       * Line 92 through 99: Just curious why someone wouldn't already have the AutoKey icons if they've gotten AutoKey from us.
If someone who's never bothered to install AutoKey because they use a Wayland desktop and AutoKey doesn't work there decides to test this code, then they wouldn't have the icons in place.  Or, if you did what I did and installed on brand new virtual machines for testing you wouldn't have them there either.

>       * Lines 100 through 113: You might want to add one additional step for folks who made some sort of configuration change they'd like to keep (like adding a new script or something) that needs to be backed up first.
That's exactly what the backup step in 3.6 is supposed to take care of.  If the user has changed the config to keep their scripts in some other path, I'm not too concerned about that.  Scripts aren't what the new AutoKey messes with.  It's the preferences file that's the real issue: ~/.config/autokey/autokey.json

2024-12-21 09:51 UTC, dlk3 commented
Explaining the window.list thing gets a little technical.  But it's interesting because it is THE reason that @sebastiansam55's code wouldn't work on X11.  It was the critical fix.

The window.list function is a thing that's actually used when you're in Wayland.  On the Wayland side it's what all the other window API functions depend on to collect all the information about the windows currently on the desktop.  As we've all mentioned, however, there never was an equivalent function in the X11 side, a completely different technique is used to get window info over there.

The way that @sebastiansam55 implemented Wayland support was to split off all of the X11 specific code into the interface.py module.  He then created an equivalent gnome_interface.py module for the Wayland side.  Which of these gets used is decided by the value set in the XDG_SESSION_TYPE environment variable.  If it's "wayland" AutoKey uses the gnome_interface.py classes and methods, it it's anything else it uses what's in interface.py  

Both of these interface modules are coded using the same underlying skeleton framework.  Python calls this an AbstractClass and it defines what methods/functions the modules based off it have to contain, even if they're implemented as  just stubs that do nothing.  The AbstractClass as @sebastiansam55 wrote it dictates that there must be a windows.list method in any module that is based off of it.  @sebastiansam55 implemented that method in the gnome_interface.py for Wayland because that's where it was needed.  He forgot to implement one in the interface.py for X11 however.  That's why the "develop" code couldn't run on X11.  There would be an exception every time AutoKey tried to use the classes defined in the interface.py module to talk to X11 because that module violated the dictates of its AbstractClass.  Running AutoKey in debug mode exposed those exception messages and made fixing this bug pretty simple.

So, the net of this is that the window.list method is in there now to keep the AbstractClass happy.  As far as I can tell so far, there's nothing on the X11 side of things that actually uses it for anything so it serves no real purpose.  I started out with just a do-nothing stub for it and that worked fine.  Later on I decided to actually implement it, just for grins.  As it is now, it returns a list of windows in the same format as that used by its Wayland-side sibling, but with a limited number of properties.  This limit is determined by what's available from the underlying call for the window list made to Wayland via the GNOME Shell.

2024-12-21 18:38 UTC, Elliria commented
I was hoping that the **GPL** thing wouldn't be a problem since the **GPL v2** notice says **GPL-2.0-or-later** and I figured the "or later" part would cover it. The problem is that the new code has no problem moving into the old code's house, but the concern is whether the old code wants to let the new code move into a room in its house.

I [asked Google](https://www.google.com/search?client=ubuntu-sn&channel=fs&q=is+it+okay+for+a+GPL3+program+to+contain+gpl+2+code) and its AI bot said that it's not okay to do that and that you should consult a lawyer [sigh]. It also made a couple of suggestions, like using alternative code, contacting the copyright holders, or checking the existing license (AutoKey's GPL) for mechanisms "that might allow for integration under certain conditions."

2024-12-21 19:19 UTC, Elliria commented
@dlk3, here are my responses to your comment:

> What I wrote in the CHANGELOG is for our internal consumption during development. When you actually go ahead and release this code (move it to "master"), then everything I've written in there should be reduced to one line: "Added support for the Wayland desktop environment" That's my opinion anyway.

Ah, okay. The way we handle that is to write the CHANGELOG content exactly as it will be in the AutoKey code-base and then put all the stuff that's for our internal consumption and write it as the comment for the PR instead. That way there won't need to be any cleanup and it will be obvious what it's for.

> I paid no attention to the license statements in these files. I learned long ago to always defer license questions to the lawyers. My guess is that as long as they're all some form of open-source license there's no real issue. Especially so if it's a question of GPLv2 vs GPLv3.

It would be fine if AutoKey used **GPL v2 or later** and you put **GPL v3** code into it. This is the other way around, though, which is why there's concern.
 
> > * **rpm-requirements.txt**: LGTM, but what's it for?
>
> It lists the prerequisite packages that have to be installed on Fedora before AutoKey will run. Nothing depends on this file, it's more along the lines of a set of notes. I thought since there was an apt-requirements for Ubuntu/Debian, there ought to be a similar file for Fedora.

Ah, okay, perfect. I'll update it above to just plain LGTM.

> > * **wayland_install.md**:
> The new "make" file I created handles all this version stuff. It installs whichever version is appropriate automagically.

Okay, that sounds good. So, can you change the text in those lines to include version 45 instead of removing that part?

> >   * In lines 11 through 19, is there a reason why you and Sam both have us cloning your repositories to test Wayland? Would the [wiki instructions for cloning a pull request](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request) work for this so that we can keep the tests local?
> 
> The reason in my case is that you have not yet pulled in my PR. Anyone who wants to test my code right now has to get it from me. There is a NOTE right in there that basically implies that this changes when you actually pull in my PR into your repo.

This is how I always test PRs. As long as there's a PR number, you can clone the repository, fetch the PR, and examine or run the code. I just did it in my virtual machine.

Here, try following [the steps in the wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request) with [this PR's numbe](https://github.com/autokey/autokey/pull/992), which is **992**, like this:
```bash
git clone https://github.com/autokey/autokey.git
cd autokey
git fetch origin pull/992/head:pull_992
git checkout pull_992
cd lib
# Run AutoKey GTK:
python3 -m autokey.gtkui -lc
# Run AutoKey Qt:
python3 -m autokey.qtui -lc
```
It should give you a working copy of your PR on your machine.

I just did it and didn't manage to load AutoKey because it got a **ModuleNotFoundError** for **puremagic**, but that can be solved by creating a **venv** and grabbing the necessary packages and/or modules, which would then give me a copy that I could test on **X11**. The fact that it's complaining about **puremagic** shows that I got your PR code by following the above steps, though.

> >   * Line 92 through 99: Just curious why someone wouldn't already have the AutoKey icons if they've gotten AutoKey from us.
> 
> If someone who's never bothered to install AutoKey because they use a Wayland desktop and AutoKey doesn't work there decides to test this code, then they wouldn't have the icons in place. Or, if you did what I did and installed on brand new virtual machines for testing you wouldn't have them there either.

Ah, that makes perfect sense!

> That's exactly what the backup step in 3.6 is supposed to take care of. If the user has changed the config to keep their scripts in some other path, I'm not too concerned about that. Scripts aren't what the new AutoKey messes with. It's the preferences file that's the real issue: ~/.config/autokey/autokey.json

Okay. That's fine.

2024-12-21 19:33 UTC, Elliria commented
> I will not merge any code that is licensed under GPL2 into the body of AutoKey. I am not the only one with merge capabilities, so the result is not final, but, if someone else does it, I will not be happy.

No worries from me. I won't merge it unless it's okay to use it and so far it looks like it isn't. Hopefully there's a way around it.
 
> I'm not going to make big deal about it, but I would still prefer that the next enhancement branch be 0.97.0. When this subject was last breached (by me), the two active developers were both against going to 1.0 because they felt the code and technicall debt didn't warrant it. Only a little of that has been improved since then. I believe @BlueDrink9 was involved with this (and maybe Thomas Hess).

It looks like you may well be right about the major version change. Google's AI bot says that major version jumps are typically for when you've introduced significant changes that break backward compatibility. Would the Wayland code break backwards-compatibility? If so, I'd be happy with **0.97.0**.

2024-12-21 19:37 UTC, Elliria commented
Interesting explanation of `get_window_list`, @dlk3. Could the list be used the way that @josephj11 [suggested](https://github.com/autokey/autokey/pull/992#issuecomment-2556566647)?

2024-12-21 22:32 UTC, josephj11 commented
@dlk3 Thanks for the detailed window list response. It gives us important context going forward.

@Elliria Hopefully, this Wayland change will be invisible to x11 users, so it shouldn't break anything for them. The only concern is that it might require new dependencies to be installed. Even if it does that, it won't break any user actions, etc. the way that switching from 0.90.4 with Python 2.x to 0.93.0 (or whatever the first version was) with Python 3.x did. That was a big change and still wasn't cnsidered enough to mandate going from 0.x to 1.0.

2024-12-21 22:55 UTC, dlk3 commented
@Elliria and @josephj11,

I've spent 35 years working around IT intellectual property lawyers at a very large IT company and what I learned is that I don't know anything about intellectual property law.  I didn't create any of the code we're talking about here

2024-12-21 23:00 UTC, dlk3 commented
@Elliria and @josephj11:
I'm gonna leave this licensing discussion up to you.  You're free to change the code I contribute in any way you like, including changing the licenses, so you should feel free do do whatever you think is necessary.

(My previous comment on this topic just a minute ago was sent by mistake, sorry for the confusion.  It's been deleted.)

2024-12-21 23:24 UTC, dlk3 commented
I have developed an autokey.spec file that allows the packaging of the "develop" branch code for installation on Fedora.  As I worked through the process of doing this I found some small bugs that needed fixing.  I also made some additional enhancements to the error message text so that they would make sense if encountered during the flow of the installation.

This commit also includes the fix for the imghdr issue on Fedora 41.  I found a better solution than what we had previously discussed.  It's better because the module used to replace imghdr is one that is supported on Fedora.  The module is called ```file-magic```.  If we were to use another module, like the puremagic one I previousl tried out, we'd have to include it in the AutoKey project to get it installed onto our users workstations.  I prefer to go with something that's already there and which the Fedora team maintains themselves.

2024-12-22 05:14 UTC, josephj11 commented
I went through the code lightly and didn't have see any issues.

One generic issue: Chris Deckter was the original author of AutoKey and we're deeply grateful for his efforts. However, he has not been a part of the  project for many years. Is there any point in still  incuding his email in the code? If we need a point of contact, it should be one of our community sites where someone can actually get support. There is currnetly no one active in the project who can be considered as it's author. We don't even have an acknowledged developer or lead developer.

I am a big fan of detailed error messages (and remedial recommendations!) like those included in this code. Most error messages are just text to throw into a web search with a hope and a prayer!

2024-12-23 05:46 UTC, dlk3 commented
This latest commit makes the same log file related changes I described in my comment in issue #709 and in the pull request I proposed for the master branch #999.

2024-12-23 12:31 UTC, Elliria commented
> This latest commit makes the same log file related changes I described in my comment in issue #709 and in the pull request I proposed for the master branch #999.

Ah, I see what you did. If, instead of adding it to this Wayland PR, you could do it on a feature branch off of **develop**, it would be a separate PR and we could put it through more quickly.

2024-12-23 13:55 UTC, Elliria commented
The license conflict seems to be a massive road-block that would have to be sorted out for this PR to move forward.

The two `.json` files below both have the same description letting you know that this extension is a fork of ickyicky's window-calls. Each of them provides a link to the [ickyicky window-calls page](https://github.com/ickyicky/window-calls). Each of them also use ickyicky's [extension.js](https://github.com/ickyicky/window-calls/blob/main/extension.js) file and it's protected by GPL 2. Unless they change the license upstream or unless we can replace this with some other code, the AutoKey project would have to hire a lawyer to sort out what can be done about the licenses.

The relevant parts of each file are in clickable details blocks below that can be expanded to see them.

<details>
	<summary>The <b>autokey-gnome-extension/44/extension.js</b> file contains a GPL comment.</summary>

  ```
  /* extension.js
   *
   * This program is free software: you can redistribute it and/or modify
   * it under the terms of the GNU General Public License as published by
   * the Free Software Foundation, either version 2 of the License, or
   * (at your option) any later version.
   *
   * This program is distributed in the hope that it will be useful,
   * but WITHOUT ANY WARRANTY; without even the implied warranty of
   * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   * GNU General Public License for more details.
   *
   * You should have received a copy of the GNU General Public License
   * along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *
   * SPDX-License-Identifier: GPL-2.0-or-later
   */
   ```

</details>

<details>
	<summary>The <b>autokey-gnome-extension/44/metadata.json</b> file contains a description with a link to a GPL-protected project.</summary>

  ```
  "description": "Adds dbus calls which can return list of windows, move, resize, close them for use with Autokey scripting. This extension is a fork of ickyicky's window-calls found at https://github.com/ickyicky/window-calls",
  ```

</details>

<details>
	<summary>The <b>autokey-gnome-extension/46/extension.js</b> file contains a GPL comment.</summary>

  ```
  /* extension.js
   *
   * This program is free software: you can redistribute it and/or modify
   * it under the terms of the GNU General Public License as published by
   * the Free Software Foundation, either version 2 of the License, or
   * (at your option) any later version.
   *
   * This program is distributed in the hope that it will be useful,
   * but WITHOUT ANY WARRANTY; without even the implied warranty of
   * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   * GNU General Public License for more details.
   *
   * You should have received a copy of the GNU General Public License
   * along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *
   * SPDX-License-Identifier: GPL-2.0-or-later
   */
  ```
</details>

<details>
	<summary>The <b>autokey-gnome-extension/46/metadata.json</b> file contains a description with a link to a GPL-protected project.</summary>

  ```
  "description": "Adds dbus calls which can return list of windows, move, resize, close them for use with Autokey scripting. This extension is a fork of ickyicky's window-calls found at https://github.com/ickyicky/window-calls",
  ```
</details>

2024-12-23 17:23 UTC, dlk3 commented
> The license conflict seems to be a massive road-block that would have to be sorted out for this PR to move forward.

I said I was gonna stay out of this but apparently I lied.

There is no road-block here.  If @josephj11 needs the GNOME extension code files to have a GPLv3 license statement, put the GPLv3 license statements in there.  What @sebastiansam55 created was a derivative work, derived from ickyicky's original code.  The GPLv2 license that ickyicky put on his original code says that any derivative work must be licensed with GPLv2 **or later**.  GPLv3 is the **or later**.  So ickyicky has given everyone permission to license their derivative works with GPLv3 if they want to.  And @josephj11 apparently wants to.

Assuming that @sebastiansam55 agrees to this change being made to his derivative code files, and I can't imagine why he wouldn't, then this is a non-issue.

2024-12-23 19:07 UTC, Elliria commented
That's perfect. The moment you mentioned derivative, you solved it and have managed to convince me. @josephj11, are you good with the AI bot's response to [this Google query](https://www.google.com/search?client=ubuntu-sn&channel=fs&q=If+you+have+a+derivative+work+derived+from+a+project%27s+code+that%27s+shared+under+GPL+2+*or+later*%2C+can+you+insert+that+code+into+your+GPL+3+or+later+project%3F) based on what @dlk3 just said? It seems fine to me.

2024-12-23 20:54 UTC, Elliria commented
This is working for me to run this PR in a cloned copy of AutoKey inside of a virtual machine that has AutoKey 0.95.0 installed on it (which made it so I didn't have to worry about dependencies):

<details>
   <summary><b>Test this PR in a clone</b></summary>

1. Clone the repository into the current directory
   ```
   git clone https://github.com/autokey/autokey.git
   ```
2. Change directory into the cloned repository:
   ```
   cd autokey
   ```
3. Fetch the pull request:
   ```
   git fetch origin pull/992/head:pull_992
   ```
4. Check out the pull request:
   ```
   git checkout pull_992
   ```
5. Create a virtual environment inside the current directory:
   ```
   python3 -m venv venv
   ```
6. Activate the virtual environment in the current shell (the prompt will change):
   ```
   source venv/bin/activate
   ```
7. Install the required pip packages:
   ```
   pip install -r pip-requirements.txt
   ```
8. Change to the lib subdirectory:
   ```
   cd lib
   ```
9. Pick one to run AutoKey:
   ```
   python3 -m autokey.gtkui -cl
   ```
   ...or...
   ```
   python3 -m autokey.qtui -cl
   ```
10. Close AutoKey.
11. Deactivate the virtual environment when finished (the prompt will change):
    ```
    deactivate
    ```
12. Delete the `autokey` directory that the clone is in or repeat step 2 followed by steps 6 through 11 to run AutoKey again at any time.

</details>

It's looking good and behaving itself so far, but I haven't stress-tested it yet.

2024-12-23 22:01 UTC, josephj11 commented
@Elliria Looks like we can set it to GPL3+ without a problem because of the "or later" provision.

All I saw in your link was a list of search results. I didn't notice anything "AI", etc. that I should look at.

2024-12-23 23:49 UTC, Elliria requested changes
* **CHANGELOG.rst**:
  * There are several versions of this file from the various commits in this PR, so I'm not sure which to review. As a result, I linked to the specific file used for any of the comments that have lines that no longer exist in the current diff so you can see exactly which lines I'm referencing.
  * Some of the changes to the files are no longer mentioned in this version of the file. Please add them back in so that this can be a complete log.
  * The version number change LGTM.
  * The detail is good on the [issue #87](https://github.com/autokey/autokey/issues/87) notes.
  * Please add a bit more detail to the **imghdr** line making it clear that you replaced **imghdr** with **file-magic**.
  * The line that starts with "Updated the Fedora installation..." contains another line that starts with "The installation process now..." which should get dropped down one line so that it's its own entry.
  * The line that starts with "The installation process now..." that was just mentioned above has more detail than is needed in the `CHANGELOG.rst` file. Can some of that detail go into a README or as a comment in the code? I like and very much appreciate the detail, but am hoping it can go elsewhere. It might also be good to put that into the [new_features.rst](https://github.com/autokey/autokey/blob/develop/new_features.rst) file, which will need to be updated before the next release, although information in that file isn't permanent.
  * Are you planning on creating a separate issue for Debian like the [issue #998](https://github.com/autokey/autokey/issues/998) that you created for Ubuntu? If so, that would satisfy this TODO and it could be removed.
  * The line about the clarity of the error messages for Wayland users LGTM.
  * The logging line LGTM.
  * [Line 35](https://github.com/autokey/autokey/pull/992/commits/5f7236217c9ebdbaf4b11a35475d9f3dc02ba081): This line can now be shortened. In answer to your comment, it looks like [the current maintainer is jonathanspw](https://packages.fedoraproject.org/pkgs/autokey/autokey-common/). 
  * [Line 37](https://github.com/autokey/autokey/pull/992/commits/5f7236217c9ebdbaf4b11a35475d9f3dc02ba081): Just the mention of the creation of the new folder should be enough to get developers to go poking around to see what's in it, so this line could be shortened.
  * General comment: Blank lines between entries aren't needed.
* **autokey-gnome-extension/44/extension.js**: The GPL change LGTM, but someone else should look over the code.
* **autokey-gnome-extension/44/metadata.json**: LGTM
* **autokey-gnome-extension/46/extension.js**: The GPL change LGTM, but someone else should look over the code.
* **autokey-gnome-extension/46/metadata.json**: LGTM
* **autokey-gnome-extension/Makefile**: Someone else should look over the code.
* **autokey-gnome-extension/README.md**: LGTM
* **autokey-user-config**: In line 52, you might want to change "Root privileges will be required to do this, running the command:" to "Root privileges will be required to do this. Running the command:"
* **autokey.spec**:
  * Why was this file moved into the new **fedora** folder?
  * Why did Python macros for openSUSE get removed from it?
  * Someone else should look over the changes to the file in its new location.
  * See also the **fedora/autokey.spec** note below.
* **debian/10-autokey.rules**:
  * Someone else should look over the code.
* **fedora/README.md**: You might want to remove yourself from lines 7, 15, 19, and 36 to make the document generic.
* **fedora/autokey.spec**:
  * Someone else should look over the diff between this version of the file and the [autkey.spec file on **develop**](https://github.com/autokey/autokey/blob/develop/autokey.spec) to compare what's new and what was removed.
  * See also the **autokey.spec** note above.
* **fedora/mkpackage**: Someone else should look over the code.
* **lib/autokey/autokey_app.py**: Accidental white-space was added in line 112.
* **lib/autokey/common.py**:
  * Line 38: The version should be **0.97.0-beta.1** since that's how we will tag it for release.
  * Line 42 and 43: Maybe we should create an autokey **Gmail** account and make the maintainer the **AutoKey team**? You'll want to weigh in on this one, @Josephj11.
* **lib/autokey/gnome_interface.py**: LGTM
* **lib/autokey/gtkapp.py**: LGTM
* **lib/autokey/gtkui/configwindow.py**: LGTM
* **lib/autokey/interface.py**: You might want to remove yourself from line 136 to make it generic. Other than that, it LGTM.
* **lib/autokey/iomediator/iomediator.py**: Neither I nor Copilot can figure out what changed on line 392. Other than that, it LGTM.
* **lib/autokey/logger.py**: LGTM
* **lib/autokey/model/abstract_abbreviation.py**: LGTM
* **lib/autokey/model/constants.py**: LGTM
* **lib/autokey/model/key.py**: LGTM
* **lib/autokey/scripting/highlevel.py**: LGTM
* **lib/autokey/uinput_interface.py**: Accidental white-space was added to line 348.
* **pip-requirements.txt**: LGTM
* **rpm-requirements.txt**: LGTM
* **setup.cfg**:
  * Line 35: This line should be deleted since we don't support **Python 3.13** yet.
* **setup.py**:
  * Line 36: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3, 9, 20**.
  * Line 37: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3, 9, 20**.
  * Line 140: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3.9**.
  * Line 186: LGTM
  * Line 194: LGTM
  * Line 213: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3.9**.
* **wayland_install.md**:
  * Lines 11 through 19: The clone instructions can use the AutoKey repository instead of yours (see steps for that are [here](https://github.com/autokey/autokey/pull/992#issuecomment-2560286087) and in [the wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request)) so that we can keep everything local to this project.
  * Lines 23 through 26: I have yet to run through all of these steps for Ubuntu to properly test them and will comment once I do.
  * Line 52: "we" should probably be "you" since you've used "you" all throughout.
  * Line 63: LGTM
  * Line 81: You'll want to add instructions beneath this line for testing `autokey.qtui`, too.
  * Line 89: You might want to replace `python3 -m autokey.gtkui -v` with `python3 -m autokey.gtkui -vc` to be consistent with line 81 (and also `python3 -m autokey.qtui -vc` once the Qt instructions are added beneath line 81).
  * Someone else should look over the Fedora steps.

2024-12-23 23:53 UTC, Elliria commented
> @Elliria Looks like we can set it to GPL3+ without a problem because of the "or later" provision.

Yep. Problem solved.
 
> All I saw in your link was a list of search results. I didn't notice anything "AI", etc. that I should look at.

You don't see a little AI section at the top of your Google search results that gives you an answer from a bot? Here's what I see when I do that search:

![GoogleBotAtTopOfResults](https://github.com/user-attachments/assets/819dd1d7-daef-49e5-ae23-6a9eb947e3af)

2024-12-24 10:03 UTC, dlk3 commented
@Elliria Thanks for looking through the PR again.  I've provided my comments below.  Just so you know my thinking ... I don't expect to contribute anything more to the develop branch until after this PR has been merged, so that things can remain stable while you and @josephj11  decide what to do.

> * **CHANGELOG.rst**:
>       
>       * There are several versions of this file from the various commits in this PR, so I'm not sure which to review. As a result, I linked to the specific file used for any of the comments that have lines that no longer exist in the current diff so you can see exactly which lines I'm referencing.

I don't understand the issue.  If you look at the diff for this file in GitHub it shows the difference between the original version that is currently in the branch and the changes that I am proposing be made to the file.  Any interim versions that may have existed as the file was gradually reworked are no longer visible in the diff.
.
>       * Some of the changes to the files are no longer mentioned in this version of the file. Please add them back in so that this can be a complete log.

I took them out for a good reason, I wanted to streamline my description of the changes I had made to make it more understandable to the reader.  The previous level of detail was too confusing in my view.  If you disagree you are more than welcome to change anything I contribute to the project, that is your role as one of the owners of the project and its contents.

>       * Please add a bit more detail to the **imghdr** line making it clear that you replaced **imghdr** with **file-magic**.

I perceive a number of comments you've made in this review as concerning stylistic or level-of-detail issues in documentation.  Rather than go back and forth on these, I think it is more efficient if you just edit the documents to suit your own preferences.  It's my view that that's one of the rights and roles a project owner/administrator has, to take incoming contributions and shape them to be consistent with the project's standards.  (I'll refer back to this response multiple times, below.)

>       * The line that starts with "Updated the Fedora installation..." contains another line that starts with "The installation process now..." which should get dropped down one line so that it's its own entry.

(Same response as above pertaining to stylistic or level-of detail issues.)

>       * The line that starts with "The installation process now..." that was just mentioned above has more detail than is needed in the `CHANGELOG.rst` file. Can some of that detail go into a README or as a comment in the code? I like and very much appreciate the detail, but am hoping it can go elsewhere. It might also be good to put that into the [new_features.rst](https://github.com/autokey/autokey/blob/develop/new_features.rst) file, which will need to be updated before the next release, although information in that file isn't permanent.

(Same response as above pertaining to stylistic or level-of detail issues.)

>       * Are you planning on creating a separate issue for Debian like the [issue #998](https://github.com/autokey/autokey/issues/998) that you created for Ubuntu? If so, that would satisfy this TODO and it could be removed.

No, Debian and Ubuntu are equivalent to me.  If you'd rather have #998 reference Debian than Ubuntu, then please feel free to make that change.  With #998 I simply wanted to make note of the things I saw when I created the installation process for Fedora.  I thought doing that might make it a little easier for the person who has to do the same thing for Debian/Ubuntu know what issues they're facing.

>       * [Line 35](https://github.com/autokey/autokey/pull/992/commits/5f7236217c9ebdbaf4b11a35475d9f3dc02ba081): This line can now be shortened. In answer to your comment, it looks like [the current maintainer is jonathanspw](https://packages.fedoraproject.org/pkgs/autokey/autokey-common/).

(Same response as above pertaining to stylistic or level-of detail issues.)

>       * [Line 37](https://github.com/autokey/autokey/pull/992/commits/5f7236217c9ebdbaf4b11a35475d9f3dc02ba081): Just the mention of the creation of the new folder should be enough to get developers to go poking around to see what's in it, so this line could be shortened.

(Same response as above pertaining to stylistic or level-of detail issues.)

>       * General comment: Blank lines between entries aren't needed.

(Same response as above pertaining to stylistic or level-of detail issues.)

>     * **autokey-user-config**: In line 52, you might want to change "Root privileges will be required to do this, running the command:" to "Root privileges will be required to do this. Running the command:"

(Same response as above pertaining to stylistic or level-of detail issues.)

>     * **autokey.spec**:
>       
>       * Why was this file moved into the new **fedora** folder?

So as to group it together in the same folder with the associated proof-of-concept script I created to build RPMs using it, and with the README.md that describes the two files.

>       * Why did Python macros for openSUSE get removed from it?

Because they are not needed.

>     * **fedora/README.md**: You might want to remove yourself from lines 7, 15, 19, and 36 to make the document generic.

(Same response as above pertaining to stylistic or level-of detail issues.)

>     * **lib/autokey/autokey_app.py**: Accidental white-space was added in line 112.

(Same response as above pertaining to stylistic or level-of detail issues.)

>     * **lib/autokey/common.py**:
>       
>       * Line 38: The version should be **0.97.0-beta.1** since that's how we will tag it for release.

I tried that and I couldn't make it work.  Python's setup process insisted on shortening "0.97.0-beta.1" to "0.97.0-b1" regardless.  Maybe someone else can figure out how to get it to do what you want.

>     * **setup.cfg**:
>       
>       * Line 35: This line should be deleted since we don't support **Python 3.13** yet.

If you want people who use the latest release of Fedora to use AutoKey then you have no choice but to support Python 3.13.  The develop branch does run on it without issue so I don't foresee any problems.  I have seen where you have said that GitHub doesn't support Python 3.13 yet.  I don't know what you are referring to when you say that.  All the GitHub documentation I've read indicates that they do support it and are currently in the process of adding support for 3.14.

>     * **setup.py**:
>       
>       * Line 36: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3, 9, 20**.
>       * Line 37: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3, 9, 20**.
>       * Line 140: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3.9**.
>       * Line 186: LGTM
>       * Line 194: LGTM
>       * Line 213: [PR #994](https://github.com/autokey/autokey/pull/994) is taking care of this with version **3.9**.

That's all well and good but those changes weren't in the setup.py that is in the base develop branch I started working from so I had to add them to my version of the code so that I could use them.  I view this as the sort conflict issue that the developer who merges pull requests into the project code decides how to handle.

>     * **wayland_install.md**:
>       
>       * Lines 11 through 19: The clone instructions can use the AutoKey repository instead of yours (see steps for that are [here](https://github.com/autokey/autokey/pull/992#issuecomment-2560286087) and in [the wiki](https://github.com/autokey/autokey/wiki/GitHub-Cheat-Sheet#local---clone-a-pull-request)) so that we can keep everything local to this project.
>       * Line 52: "we" should probably be "you" since you've used "you" all throughout.
>       * Line 81: You'll want to add instructions beneath this line for testi [...]

2024-12-24 23:36 UTC, pat-richter commented
I've tried to run this with Fedora 41 Silverblue. I've probably messed something up, but I have several issues.

I really want to emulate mouse.scroll_up/down with my keyboard but was not yet able to do it


# Issues

- phrases seems to work, scripts seems not to work
- was not able to activate keyboard AND external keyboard, only one or another
- can't save, seems an issue with the UI at all (see below "can't go left when clicked right)

# Logs

## Start Up

```
patrick@fedora:~/.config/autokey$ autokey-start 
2024-12-24 23:46:16,093 INFO - autokey.UI_common_functions - Commandline program "visgrep" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "visgrep" exists on your system and is in the $PATH seen by Autokey.
2024-12-24 23:46:16,093 INFO - autokey.UI_common_functions - Commandline program "png2pat" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "png2pat" exists on your system and is in the $PATH seen by Autokey.
2024-12-24 23:46:16,093 INFO - autokey.autokey_app - Initialising application
2024-12-24 23:46:16,097 INFO - autokey.autokey_app - Initialise global hotkeys
2024-12-24 23:46:16,097 INFO - autokey.configmanager.configmanager - Loading config from existing file: /var/home/patrick/.config/autokey/autokey.json
2024-12-24 23:46:16,097 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.97.0b1
2024-12-24 23:46:16,098 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/patrick/.config/autokey/data/My Phrases'
2024-12-24 23:46:16,099 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/patrick/.config/autokey/data/Sample Scripts'
2024-12-24 23:46:16,099 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/patrick/.config/autokey/data/My Phrases1'
2024-12-24 23:46:16,100 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/patrick/.config/autokey/data/Sample Scripts1'
2024-12-24 23:46:16,103 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/patrick/.config/autokey/data/MyScripts'
2024-12-24 23:46:16,103 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/My Phrases
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/My Phrases/Addresses
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/Sample Scripts
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/My Phrases1
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/My Phrases1/Addresses
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/Sample Scripts1
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Phrases
2024-12-24 23:46:16,103 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Phrases/Demo
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Phrases/Demo/Addresses
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Phrases/Obsidian
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Phrases/Global
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Actions
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Actions/Scroll
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data/MyScripts/Actions/Google Docs
2024-12-24 23:46:16,104 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey/data
2024-12-24 23:46:16,104 DEBUG - autokey.monitor - Adding watch for /var/home/patrick/.config/autokey
2024-12-24 23:46:16,104 DEBUG - autokey.configmanager.configmanager - Global settings: {'isFirstRun': False, 'serviceRunning': True, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [2240, 1318], 'hPanePosition': 561, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status-dark', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [], 'scriptGlobals': {}, 'gtkTheme': 'tango', 'gtkExpandedRows': ['1', '0', '2', '3', '2:0', '2:1', '2:1:0', '2:1:1', '2:1:0:0', '2:0:0', '2:1:2', '2:0:1'], 'pathLastOpen': '2:0:1:0', 'keyboard': '/dev/input/event22', 'mouse': '/dev/input/event6', 'devices': ['/dev/input/event5', '/dev/input/event6'], 'uinputDelay': 0.5}
2024-12-24 23:46:16,104 INFO - autokey.service - Starting service
2024-12-24 23:46:16,104 DEBUG - autokey.iomediator.iomediator - Using gnome extension window interface
2024-12-24 23:46:16,107 DEBUG - autokey.gnome_interface - AutoKey Gnome Extension version: 0.1
2024-12-24 23:46:17,134 INFO - autokey.uinput_interface - input User membership good!
2024-12-24 23:46:17,136 INFO - autokey.uinput_interface - Grabbing keyboard from settings: /dev/input/event22
2024-12-24 23:46:17,509 INFO - autokey.uinput_interface - Grabbing mouse from settings: /dev/input/event6
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: Power Button
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: Sleep Button
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: Lid Switch
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: Power Button
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: AT Translated Set 2 keyboard
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ELAN010D:00 04F3:3300 Mouse
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ELAN010D:00 04F3:3300 Touchpad
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: Video Bus
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ELAN25D0:00 04F3:432C
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ELAN25D0:00 04F3:432C UNKNOWN
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ELAN25D0:00 04F3:432C UNKNOWN
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: PC Speaker
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HP WMI hotkeys
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic HDMI/DP,pcm=3
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic HDMI/DP,pcm=7
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic HDMI/DP,pcm=8
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic HDMI/DP,pcm=9
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic Mic
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: HD-Audio Generic Headphone
2024-12-24 23:46:17,510 DEBUG - autokey.uinput_interface - Found device: ydotoold vi [...]

2024-12-25 02:48 UTC, josephj11 commented
@Elliria Responses to your long review post:

I keep a "20" in Python versions. What's that about?

Since Ubuntu (and many others) are derived from Debian. Any notes/comments, etc. should refer to Debian and not to Ubuntu unless there is a specific reason not to do so. That being said, it's not a really big deal.

I'm not sure how release tags work. I don't remember how the betas were done for 0.96. Did it involve "tagging" a release and causing all the GitHub  actions to run creating debs, etc. Looks like it dd. That's an announcement to the world of a new release.  I'm running 0.96.0-beta.10 because I was too lazy to formally update to the release that had idenitcal code. But, that's internal to AutoKey and not a GitHub tag. The debs are tagged as prerelease on GitHub somehow.

AutoKey gmail  account: We  could, but it's one more place to check and maintain. If we can send people to somewhere  that alread exists like our Google Groups forum or Gitter, that woud be better IMO.
`autokey-users@googlegroups.com`  works for me.

You have a number of legitimate comments that someone else should look at the code. Maybe we should tag our lurking developers. Other than Bluedrink9, they're all we've got  ATM. I assume BD sees all of this activity and would comment if he felt moved to.

I see the AI summary in Google now that I know it's there. I almost never use Google search and didn't notice it.

2024-12-25 10:57 UTC, dlk3 commented
> I've tried to run this with Fedora 41 Silverblue. I've probably messed something up, but I have several issues.

@pat-richter Thanks so much for taking the time to test out this new code.  I'm sure everyone here is very grateful for your willingness to help out, I know that I am.
 
> I really want to emulate mouse.scroll_up/down with my keyboard but was not yet able to do it. I've done it without toolbox since it seems that my onput was not given into it correctly. so rpm-ostree for packages and user level install of autokey

I have not done a lot of testing with the mouse functions in AutoKey, mostly because I don't use that capability myself and therefore don't have any test cases.  Can you attach a sample script that shows what you're trying to do? (I assume you are doing this with scripts?)

> # Issues
> 
>     * phrases seems to work, scripts seems not to work

I can't reproduce this problem.  My scripts all work fine on Fedora 41 Workstation.  Can you attach an example of a script that doesn't work?  

>     * was not able to activate keyboard AND external keyboard, only one or another

That is working as designed, unfortunately.  As you discovered, AutoKey under Wayland/GNOME can only attach to one keyboard at a time.

>     * can't save, seems an issue with the UI at all (see below "can't go left when clicked right)

Sorry, I cannot reproduce this problem either.  I don't see the exceptions that you do.  And I am not sure that I understand the problem that you are describing.  I am able to save my changes in the UI and I have no problem switching between the left and right panels.  Can you give me more of a step-by-step guide to reproducing the problem you are seeing, to help me reproduce it here on my system?  Also, please add the "-v" option to the command line you are using to start AutoKey.  Then, after reproducing the problem on your system, attach the log file that you find at ${HOME}/.local/share/autokey/autokey.log.  This will save you having to do the cut-and-paste of the console messages.

Thanks.

2024-12-26 00:37 UTC, pat-richter commented
OK, I've created a new Silverblue instance. Just for notes, this is the setup (chech the deps for your guide @dlk3 some were missing for me)

# Guide

## Install system dependencies
rpm-ostree install gcc gcc-c++ git make cmake dbus-glib-devel python3-devel cairo-devel gobject-introspection-devel cairo-gobject-devel gtksourceview3 gtksourceview3-devel zenity python3-gobject

## Reboot after rpm-ostree installation
systemctl reboot

## Create and activate virtual environment
mkdir -p ~/.local/autokey
python -m venv ~/.local/autokey/venv
source ~/.local/autokey/venv/bin/activate

## Clone repository
mkdir -p ~/src
cd ~/src
git clone https://github.com/dlk3/autokey --branch wayland

## Install Python requirements
cd ~/src/autokey
pip install packaging pyasyncore evdev
pip install -r pip-requirements.txt

## Install GNOME Shell extension
cd ~/src/autokey/autokey-gnome-extension
make
gnome-extensions install autokey-gnome-extension@autokey.zip

## Configure uinput interface
sudo mkdir -p /etc/udev/rules.d
sudo tee /etc/udev/rules.d/10-autokey.rules > /dev/null <<EOF
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", GROUP="input", MODE="0660"
EOF

## Add user to input group (requires system configuration)
sudo mkdir -p /etc/systemd/system/user@.service.d/
sudo tee /etc/systemd/system/user@.service.d/groups.conf << EOF
[Service]
SupplementaryGroups=input
EOF

## Reload systemd and reboot
sudo systemctl daemon-reload
systemctl reboot

## Reboot; Run user configuration
~/src/autokey/autokey-user-config

## Log Out and In; Run Autokey
source ~/.local/autokey/venv/bin/activate
cd ~/src/autokey/lib
python3 -m autokey.gtkui -v

# I still get an error... log below

```
2024-12-26 01:31:50,710 INFO - autokey.UI_common_functions - Commandline program "visgrep" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "visgrep" exists on your system and is in the $PATH seen by Autokey.
2024-12-26 01:31:50,710 INFO - autokey.UI_common_functions - Commandline program "png2pat" was not found/able to be used correctly by AutoKey. This program is optional for Autokey operation, but if you wish to use functionality associated with it, Check that "png2pat" exists on your system and is in the $PATH seen by Autokey.
2024-12-26 01:31:50,736 INFO - autokey.autokey_app - Initialising application
2024-12-26 01:31:50,738 INFO - autokey.autokey_app - Initialise global hotkeys
2024-12-26 01:31:50,739 INFO - autokey.configmanager.configmanager - Loading config from existing file: /var/home/pat/.config/autokey/autokey.json
2024-12-26 01:31:50,739 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.97.0b1
2024-12-26 01:31:50,740 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/pat/.config/autokey/data/My Phrases'
2024-12-26 01:31:50,740 DEBUG - autokey.configmanager.configmanager - Loading folder at '/var/home/pat/.config/autokey/data/Sample Scripts'
2024-12-26 01:31:50,740 INFO - autokey.configmanager.configmanager - Configuration changed - rebuilding in-memory structures
2024-12-26 01:31:50,740 DEBUG - autokey.monitor - Adding watch for /var/home/pat/.config/autokey/data/My Phrases
2024-12-26 01:31:50,741 DEBUG - autokey.monitor - Adding watch for /var/home/pat/.config/autokey/data/My Phrases/Addresses
2024-12-26 01:31:50,741 DEBUG - autokey.monitor - Adding watch for /var/home/pat/.config/autokey/data/Sample Scripts
2024-12-26 01:31:50,741 INFO - autokey.configmanager.configmanager - Successfully loaded configuration
2024-12-26 01:31:50,741 DEBUG - autokey.monitor - Adding watch for /var/home/pat/.config/autokey/data
2024-12-26 01:31:50,741 DEBUG - autokey.monitor - Adding watch for /var/home/pat/.config/autokey
2024-12-26 01:31:50,741 DEBUG - autokey.configmanager.configmanager - Global settings: {'isFirstRun': False, 'serviceRunning': False, 'menuTakesFocus': False, 'showTrayIcon': True, 'sortByUsageCount': True, 'promptToSave': False, 'enableQT4Workaround': False, 'interfaceType': 'XRecord', 'undoUsingBackspace': True, 'windowDefaultSize': [600, 400], 'hPanePosition': 150, 'columnWidths': [150, 50, 100], 'showToolbar': True, 'notificationIcon': 'autokey-status', 'workAroundApps': '.*VirtualBox.*|krdc.Krdc', 'triggerItemByInitial': False, 'disabledModifiers': [], 'scriptGlobals': {}, 'gtkTheme': 'classic', 'gtkExpandedRows': [], 'pathLastOpen': '0', 'keyboard': None, 'mouse': None, 'devices': [], 'uinputDelay': 0.5}
2024-12-26 01:31:50,741 INFO - autokey.service - Starting service
2024-12-26 01:31:50,741 DEBUG - autokey.iomediator.iomediator - Using gnome extension window interface
2024-12-26 01:31:50,744 DEBUG - autokey.gnome_interface - AutoKey Gnome Extension version: 0.1
2024-12-26 01:31:51,762 ERROR - autokey.uinput_interface - User not in input group add yourself or run program as root
2024-12-26 01:31:51,763 ERROR - autokey.uinput_interface - sudo usermod -a -G input pat
2024-12-26 01:31:51,763 ERROR - autokey.autokey_app - Error starting interface: User not in "input" user group, add yourself with the "autokey-user-config" command
Traceback (most recent call last):
  File "/var/home/pat/src/autokey/lib/autokey/autokey_app.py", line 200, in __try_start_service
    self.service.start()
    ~~~~~~~~~~~~~~~~~~^^
  File "/var/home/pat/src/autokey/lib/autokey/service.py", line 91, in start
    self.mediator = self.__start_new_IoMediator()
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/var/home/pat/src/autokey/lib/autokey/service.py", line 99, in __start_new_IoMediator
    mediator = IoMediator(self)
  File "/var/home/pat/src/autokey/lib/autokey/iomediator/iomediator.py", line 82, in __init__
    self.interface = UInputInterface(self, self.app)
                     ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/var/home/pat/src/autokey/lib/autokey/uinput_interface.py", line 187, in __init__
    self.validate()
    ~~~~~~~~~~~~~^^
  File "/var/home/pat/src/autokey/lib/autokey/uinput_interface.py", line 347, in validate
    raise Exception("User not in \"input\" user group, add yourself with the \"autokey-user-config\" command")
Exception: User not in "input" user group, add yourself with the "autokey-user-config" command
2024-12-26 01:31:51,765 DEBUG - autokey.gtkapp - Displaying GTK_MESSAGE_ERROR Dialog
2024-12-26 01:31:54,257 INFO - autokey.autokey_app - Creating DBus service
2024-12-26 01:31:54,258 DEBUG - autokey.dbus_service - Created DBus service
2024-12-26 01:31:54,258 DEBUG - autokey.autokey_app - DBus service created
2024-12-26 01:31:54,258 INFO - autokey.autokey_app - ----- AutoKey Usage Statistics -----
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Phrase: 9c9d1674, Usage Count: 0 []
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Phrase: 4ae92ff1, Usage Count: 0 []
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Phrase: 022dcaac, Usage Count: 0 []
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Phrase: 19c44d15, Usage Count: 0 []
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Script: 2e5d8b92, Usage Count: 0 {('system', 'exec_command'): 1, ('keyboard', 'send_keys'): 1}
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Script: 129ad970, Usage Count: 0 {('dialog', 'list_menu'): 1, ('keyboard', 'send_keys'): 1}
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Script: 09a4c5ea, Usage Count: 0 {('clipboard', 'get_selection'): 1, ('keyboard', 'send_key'): 1, ('keyboard', 'send_keys'): 1}
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Script: 55ac59ff, Usage Count: 0 {('clipboard', 'get_selection'): 1, ('dialog', 'input_dialog'): 1, ('engine', 'get_folder'): 1, ('engine', 'create_abbreviation'): 1}
2024-12-26 01:31:54,259 INFO - autokey.autokey_app - Script: c64c32db, Usage Count: 0 {('clipboard', 'get_selection'): 1, ('engine', 'get_folder'): 1, ('engine', 'create_phrase'): 1}
2024-12-26 01:31:54,259 INFO - autokey.aut [...]

2024-12-26 08:16 UTC, josephj11 commented
@pat-richter Welcome to the AutKey cmmunity!

I'll let David  handle the hard parts.

I'm not up on the niceties of systemd. What output do you get from 

```
groups
```
`input` should be listed for your user. I think

```
sudo addgroup input
```

wull work if the systemctl magic didn't.

The rest of the messages seem to be related to the "Higher Level" API dependencies which are optional.

I just opened #1001 to get those eliminated because that feature probably won't work at all under Wayland.

2024-12-26 08:22 UTC, pat-richter commented
LOL, hey @josephj11 

just wanted to add that I'm in the group 5 min ago. kids...

(venv) pat@fedora:~/src/autokey/lib$ groups
pat wheel input

2024-12-26 08:22 UTC, pat-richter commented
LOL, hey @josephj11 

just wanted to add that I'm in the group 5 min ago. kids...

(venv) pat@fedora:~/src/autokey/lib$ groups
pat wheel input

2024-12-26 09:11 UTC, josephj11 commented
@dlk3 Looks like Wayland generates a lot of new log messages. 

What are all the  ones like autokey.autokey_app - Script: 55ac59ff, Usage Count: ` about?

I do a lot of support involving reading traces, so I need t know what I'm lookijng at.

2024-12-26 09:14 UTC, josephj11 commented
The fixes for x11 and Fedora should really be separated. We need to be able to look back on changes like these as atomically as possible.

2024-12-26 12:19 UTC, dlk3 commented
> What are all the ones like autokey.autokey_app - Script: 55ac59ff, Usage Count: ` about?

Those messages all come under this heading in the log:
```
2024-12-26 06:13:29,543 INFO - autokey.autokey_app - ----- AutoKey Usage Statistics -----
```
These messages report how many times a defined phrase, script, or folder has been invoked.  The counts are cumulative over time and come from the "usageCount" element in each of the individual *.json files in the data directory tree (```~/.config/autokey/data``` plus whatever other paths the user may have added.)  The log entries for scripts end with an array that contains the counts of the number of times that specifc AutoKey APIs calls are used in the script.   Similarly, the log entries for phrases end with an array that counts the AutoKey macros used in the phrase.

The "55ac59ff" in your sample log entry is a hash of the name of the item.  I have no idea why they decided to log an unintelligible hash of the item's name.  A simple three-line patch would change that so that the human-readable item name was logged instead.
```
diff --git a/lib/autokey/autokey_app.py b/lib/autokey/autokey_app.py
index e8ae1ad..31fac5c 100644
--- a/lib/autokey/autokey_app.py
+++ b/lib/autokey/autokey_app.py
@@ -131,13 +131,13 @@ class AutokeyApplication:
         for item in self.configManager.allItems:
             if type(item) is autokey.model.phrase.Phrase:
                 # logger.info(item.description, item.usageCount, item.phrase)
-                logger.info(f"Phrase: {get_digest(item.description)}, Usage Count: {item.usageCount} {self.getMacroUsage(item.phrase)}")
+                logger.info(f"Phrase: {item.description}, Usage Count: {item.usageCount} {self.getMacroUsage(item.phrase)}")
             elif type(item) is autokey.model.script.Script:
-                logger.info(f"Script: {get_digest(item.description)}, Usage Count: {item.usageCount} {self.getAPIUsage(item.code)}")
+                logger.info(f"Script: {item.description}, Usage Count: {item.usageCount} {self.getAPIUsage(item.code)}")
         
         for item in self.configManager.allFolders:
             
-            logger.info(f"Folder: {get_digest(item.title)}, Usage Count: {item.usageCount}")
+            logger.info(f"Folder: {item.title}, Usage Count: {item.usageCount}")
 
         logger.info("----- AutoKey Usage Statistics -----")
```

2024-12-26 13:05 UTC, dlk3 commented
@pat-richter Your setup all looks good but the error message is indicating that AutoKey cannot access the /dev/uinput device on your system for some reason.  The message is assuming that maybe you forgot to add your user to the "input" user group, or forgot to log out/in after, but it looks like you did all that.   You've proved your id is in fact in the group with the ```groups``` command.  You could check the access set on the device by doing ```ls -l /dev/uinput```  to confirrn that its access is set to ```crw-rw----*``` and it is assigned to the "input" group.  If those settings aren't in place, you should check the ```/etc/udev/rules.d/10-autokey.rules``` file you created during setup.  That's how those settings get put in place at boot time.

In the meantime I'll try setting up a Silverblue VM and repeating the process you've described here to see if I can reproduce the problem.

One comment on your setup process:  I don't understand what is going on with the systemd config file you've created.  I couldn't find any documentation on adding users to groups that way.  As I understand it, SupplementaryUsers is used to give a service running under systemd access to resources accessible to specific user groups.  I can't find anywhere where it talks about using it to add users to groups.  But, this isn't a critical issue.  As you've shown, your id is indeed in the "input" group and that's what matters.  The ```autokey-user-config``` script you ran is what's meant to do that.

2024-12-26 13:25 UTC, dlk3 commented
@pat-richter It looks like this might be a Silverblue-specific problem related to the way that it manages user groups.  Check out [this explanation](https://community.endlessos.com/t/how-do-i-add-myself-to-the-group-input/18976/4).  If that solves your problem then I can change the ```autokey-user-config``` script to sccount for it.

(I'm still in the middle of setting up my own Silverlblue VM so I can confirm this.)

2024-12-26 13:39 UTC, Elliria commented
> > ```
> > * **lib/autokey/common.py**:
> >   
> >   * Line 38: The version should be **0.97.0-beta.1** since that's how we will tag it for release.
> > ```
> 
> I tried that and I couldn't make it work. Python's setup process insisted on shortening "0.97.0-beta.1" to "0.97.0-b1" regardless. Maybe someone else can figure out how to get it to do what you want.

Interesting. The [most recent beta's lib/autokey/commpon.py file's VERSION line](https://github.com/autokey/autokey/blob/v0.96.0-beta.10/lib/autokey/common.py#L36) is **0.96.0-beta.10** and I just cloned AutoKey, did `git checkout v0.96.0-beta.10`, ran AutoKey, clicked the **Help** menu, and chose **About** to see if it was changed there and it gave me the full version. I wonder what has changed in the code to make it impossible for you to specify that.

![v0 96 0-beta10](https://github.com/user-attachments/assets/94b893bc-5019-4014-b428-96a9555eab29)

2024-12-26 13:43 UTC, Elliria commented
> > ```
> > * **setup.cfg**:
> >   
> >   * Line 35: This line should be deleted since we don't support **Python 3.13** yet.
> > ```
> 
> If you want people who use the latest release of Fedora to use AutoKey then you have no choice but to support Python 3.13. The develop branch does run on it without issue so I don't foresee any problems. I have seen where you have said that GitHub doesn't support Python 3.13 yet. I don't know what you are referring to when you say that. All the GitHub documentation I've read indicates that they do support it and are currently in the process of adding support for 3.14.

We use the **Python** version range that **GitHub** supports for the **most-recent Ubuntu release**. You can always find it in the **Python** section inside of the **Cached Tools** section found in the **Included Software** link for the most-recent Ubuntu release (the top one listed) on [GitHub's runner-images](https://github.com/actions/runner-images#available-images) page.

2024-12-26 13:58 UTC, Elliria commented
@josephj11: 
 
> I keep a "20" in Python versions. What's that about?

I see that you sorted that out elsewhere.
 
> Since Ubuntu (and many others) are derived from Debian. Any notes/comments, etc. should refer to Debian and not to Ubuntu unless there is a specific reason not to do so. That being said, it's not a really big deal.

I was under the impression that our build is primarily for Ubuntu. Even our former lead developer was uncomfortable messing with the Debian part of the AutoKey code-base. It would be nice if we brought in someone who's comfortable with the Debian requirements.
 
> I'm not sure how release tags work. I don't remember how the betas were done for 0.96. Did it involve "tagging" a release and causing all the GitHub actions to run creating debs, etc. Looks like it dd. That's an announcement to the world of a new release. I'm running 0.96.0-beta.10 because I was too lazy to formally update to the release that had idenitcal code. But, that's internal to AutoKey and not a GitHub tag. The debs are tagged as prerelease on GitHub somehow.

We would create a tag and then the workflow would react to that tag by creating a beta release. And **prerelease** is set by the [build.yml](https://github.com/autokey/autokey/blob/master/.github/workflows/build.yml#L156-L163) workflow automatically as part of the build process.
 
> AutoKey gmail account: We could, but it's one more place to check and maintain. If we can send people to somewhere that alread exists like our Google Groups forum or Gitter, that woud be better IMO. `autokey-users@googlegroups.com` works for me.

That's perfect. Would you and I see it automatically or would we have to deliberately check that email account?

> You have a number of legitimate comments that someone else should look at the code. Maybe we should tag our lurking developers. Other than Bluedrink9, they're all we've got ATM. I assume BD sees all of this activity and would comment if he felt moved to.

It looks like they're already tagged.
 
> I see the AI summary in Google now that I know it's there. I almost never use Google search and didn't notice it.

It's interesting and often useful.

2024-12-26 14:45 UTC, dlk3 commented
@pat-richter I was able to reproduce your problem on a Silverblue VM.  I even tried the systemd setup you described and it did indeed add my user to the "input" group.  So that's news to me and since I like to learn a new thing every day, yea for you!!

The source of the problem did turn out to be the fact that Silverblue's user groups setup is different, like the link I found suggested.  If I add the "input" user group's definition to ``/etc/group``` then AutoKey starts up without error.  The line I added looks like this ("dlk" is my userid.)
```
input:x:104:dlk
```
Give it a try and let me know ...

2024-12-26 15:17 UTC, dlk3 commented
@Elliria 
> > > ```
> > > * **lib/autokey/common.py**:
> > >   
> > >   * Line 38: The version should be **0.97.0-beta.1** since that's how we will tag it for release.
> > > ```
> > 
> > 
> > I tried that and I couldn't make it work. Python's setup process insisted on shortening "0.97.0-beta.1" to "0.97.0-b1" regardless. Maybe someone else can figure out how to get it to do what you want.
> 
> Interesting. The [most recent beta's lib/autokey/commpon.py file's VERSION line](https://github.com/autokey/autokey/blob/v0.96.0-beta.10/lib/autokey/common.py#L36) is **0.96.0-beta.10** and I just cloned AutoKey, did `git checkout v0.96.0-beta.10`, ran AutoKey, clicked the **Help** menu, and chose **About** to see if it was changed there and it gave me the full version. I wonder what has changed in the code to make it impossible for you to specify that.

Sorry, I guess I could have been clearer.  You are correct, the version variable in common.py can be set to anything you want and that will show up unchanged in the About panel.  What I was referring to was what pythonsetup will do to that string when you build and install the code on the system, and how the version number would subsequently show up when you do a "pip list" or "apt" query.  I thought it best that those version numbers all be the same in all those locations.  But that's up to you.  I'd suggest working out exactly what you want once you have a chance to see what happens to the version numbers when you are testing whatever release building procedure you're going to use.

2024-12-26 20:39 UTC, pat-richter commented
@dlk3 indeed, this worked. I've updated the guide above, also adding the new dep to install.

I still have to run the `python3 -m autokey.gtkui -v` two times for the window to appear for whatever reason. 

Maybe this causes the issue.
`(__main__.py:3006): Gtk-CRITICAL **: 21:37:49.110: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`


While I can run some demo scripts like echo time, I'm not able to do my specific binding for `mouse.scroll_down(2)`. I think this is how it should work and I did this before. May you test if you can scroll with key combination like leftmeta+x?

2024-12-26 20:55 UTC, josephj11 commented
@dlk3 Thanks for the info about the log entries. Don't waste time looking, but do you happen to know when those log messages were added to AutoKey?

They don't look very familiar. From your perspective, what are these entries good for? They look interesting, but it's not obvious to me. I need to know that before forming an opinion as to whether they should be modified/enhanced or suppressed.

@Elliria I got the forum gmail email address by looking at the messages I already have in my AutoKey folder in Thunderbird, so if you see those messages now, you should see any new ones from users getting the address from our code. The forum requires validating new users. If they post, I get an email asking me to approve their post as a non-member. If they join, I do not get a message, so I frequently find join requests that are pretty old.

@pat-richter By default, AutoKey starts without displaying its main window. If it's already running (in the background) and you run it again, the new instance displays the main menu and exits. If you want it to display the main menu the first time you start it, specify the `-c` flag on the command line. Most of the time users will automatically start AutoKey just to use it, so the main window would not be needed. That's only useful when you want to change something or need to look up a hotkey/trigger phrase you don't remember...

2024-12-27 00:20 UTC, dlk3 commented
@josephj11 
The usage stats log lines probably wouldn't look familiar to you as this code is only in the develop branch.  @sebastiansam55 added it in April 2023 (see below.)  I can see it being helpful if you're trying to troubleshoot someone else's config via their log.  You can see their configuration of phrases and scripts and the APIs they are using without having to ask them to ship you their files.  This is information that might be helpful in certain cases.  This stuff only appears in the log once, when you first start AutoKey, so I don't see it as being unduly burdensome.

```
$ git log -p -S "Usage Statistics"
commit 7b8aef6c5ad83d35c42e5093b1a55f1e46e316a4
Author: Sam Sebastian <sebastiansam55@gmail.com>
Date:   Fri Apr 28 17:28:56 2023 -0400

    API and macro usage statistics

[snip]
```

2024-12-27 00:45 UTC, dlk3 commented
@pat-richter said:
> While I can run some demo scripts like echo time, I'm not able to do my specific binding for `mouse.scroll_down(2)`. I think this is how it should work and I did this before. May you test if you can scroll with key combination like leftmeta+x?

Ok, got it, thanks.  I'll see what I can figure out.  I haven't been into that part of the code yet, @sebastiansam55 is the guy who actually wrote all this, I've just been debugging parts of it to see if would work and I'm new to the code.

2024-12-27 01:47 UTC, josephj11 commented
@dlk3 Thanks. In that case, use the names or hashes, whatever makes the log entries more useful.

Does the log show the AutoKey version anywhere? It would be usefull to have it at the begiining and just before shutdown because a lot of pasted traces just show the end where everything interesting occurred. This can be a separate enhancement issue if desired.

2024-12-27 02:10 UTC, dlk3 commented
@josephj11 
The version is logged when AutoKey starts, but not when it terminates.
```
2024-12-26 11:31:03,662 INFO - autokey.configmanager.version_upgrading - Checking if upgrade is needed from version 0.97.0-beta1
```

2024-12-27 03:30 UTC, dlk3 commented
@pat-richter said:
> While I can run some demo scripts like echo time, I'm not able to do my specific binding for `mouse.scroll_down(2)`. I think this is how it should work and I did this before. May you test if you can scroll with key combination like leftmeta+x?
 
I tested mouse scrolling on both Fedora 40 Workstation and Fedora 41 Silverblue and it works, with a caveat.  

I tested first on Workstation.  If I used metakey-x as my hotkey, scrolling doesn't behave like I'd expect it to.  AutoKey sent the mouse.scroll_down(2) "keystrokes" so fast that my desktop saw them as metakey-scroll_down keystrokes, because a human can't release the metakey fast enough.  Doing metakey-scroll_down on my Workstation moves me one workspace to the right, and the metakey-x script did exactly that.  If I used a special key that didn't enable special mouse wheel functions, like the alt key for example, then alt-x performed the mouse.scroll_down(2) as expected, the window that had focus scrolled down a little.

I then tested the script with alt-x as my hotkey on Silverblue to confirm that this would work there and it did.

So, my answer is, avoid using hotkey combinations that contain keys that themselves affect the way that the mouse behaves.  I don't believe there's a way to get around this.

I have only tested this under Wayland.  I have not regression tested it under X11 or on older versions of AutoKey.

2024-12-27 06:04 UTC, pat-richter commented
> @pat-richter By default, AutoKey starts without displaying its main window. If it's already running (in the background) and you run it again, the new instance displays the main menu and exits. If you want it to display the main menu the first time you start it, specify the -c flag on the command line. Most of the time users will automatically start AutoKey just to use it, so the main window would not be needed. That's only useful when you want to change something or need to look up a hotkey/trigger phrase you don't remember...

Makes sense. Never noticed this, as it was started on start. Thanks.

> I then tested the script with alt-x as my hotkey on Silverblue to confirm that this would work there and it did.

Ok, I'll test it again tonight. The Metakey issue is not unexpected (although I will disable this key combination so scroll will just work)

Have a good day

2024-12-27 13:35 UTC, dlk3 commented
@pat-richter said:
> ```
> keyboard.release_key("<left_meta>")
> mouse.scroll_down(2)
> ```
Excellent!  That's a much better answer than mine.  <grin>

I thought I had tested the release_key() technique in another context and it didn't work.  But it certainly does work here.  Very cool.

2024-12-27 21:00 UTC, josephj11 commented
@pat-richter If you get a chance, it would be great if you could add this to our wiki being sure to incude Wayland in the title. We'll need a Wayland section there eventually.

Thanks for working on this.

2024-12-28 00:08 UTC, dlk3 commented
@josephj11 The script trick that @pat-richter found applies just as much under X11 as it does under Wayland.  It's a great idea to document it as a general technique, but I don't think we want to segregate it into a new Wayland section in the wiki.  I'm sure we'll eventually find some things that are unique to Wayland, and will create that new section then, but I don't think we've found anything yet that warrants that.

I'll go ahead and write it up in the wiki.  Least I can do after @pat-richter went to the effort to test the code and found a great trick.

2024-12-28 08:20 UTC, josephj11 commented
@dlk3 Great! My mistake. Remember to add links to your wiki entry in the contents index(es).

It's much easier to keep track of  thungs we figure out in the wiki instead of  searching for them in the rest of our GitHub pages. All sort of good things get buried in our discussions here (including some by me).

2024-12-30 19:50 UTC, dlk3 commented
@pat-richter In regards to you having to run AutoKey twice to get the window to appear:  Do you have a system tray extension installed in your Gnome?  If you don't, that could explain the problem.  I wrote about this in a **Note** in [Step 4 of the wayland_install.md doc](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md#4-installing-the-autokey-icons).

If there's no tray on your desktop then AutoKey has no place to display its icon when you start it up the first time.  And then when you run it for the second time it will see that it's already running and pop its main window.  Details on what to do are at that URL, as well as instructions on how to install the icons so that AutoKey looks nice on the tray, once you've got a tray.

2024-12-31 00:17 UTC, josephj11 commented
Tangential issue: (just to keep in mind if you see anything that changes this)

Under Qt, left clicking the  panel icon opens the main  menu and right clicking on it opens the context menu. Under GTK, left and right clicks open the context menu. This was researched and there didn't seem to be any way to get the left click to work like it does in Qt.

2025-01-08 19:39 UTC, Elliria commented
@dlk3:

> Sorry, I guess I could have been clearer. You are correct, the version variable in common.py can be set to anything you want and that will show up unchanged in the About panel. What I was referring to was what pythonsetup will do to that string when you build and install the code on the system, and how the version number would subsequently show up when you do a "pip list" or "apt" query. I thought it best that those version numbers all be the same in all those locations. But that's up to you. I'd suggest working out exactly what you want once you have a chance to see what happens to the version numbers when you are testing whatever release building procedure you're going to use.

It sounds like something is broken somewhere if versions that we specify are being altered. I would definitely stick with **0.97.0-beta.1** since that's how we tag it for release and how we've done it in all previous releases.

2025-01-08 19:49 UTC, Elliria commented
@josephj11:

> @Elliria I got the forum gmail email address by looking at the messages I already have in my AutoKey folder in Thunderbird, so if you see those messages now, you should see any new ones from users getting the address from our code. The forum requires validating new users. If they post, I get an email asking me to approve their post as a non-member. If they join, I do not get a message, so I frequently find join requests that are pretty old.

Ah, okay. In that case, on second thought, I don't think that would work as the AutoKey email address since it's a public forum rather than a private email address. Although the privacy of email is questionable at best, a user who writes to an email address should be able to have an expectation of a reasonable amount of privacy. If they email you, it should be between them and you and not between them and the world.

We'd probably be better off creating a a Gmail account for AutoKey. I asked the Google AI bot and it said a free, open-source project wouldn't have to pay for a Gmail account. And as long as its IMAP, more than one of us could access and manage it.

2025-01-08 19:56 UTC, Elliria commented
@dlk3

> >   * Why did Python macros for openSUSE get removed from it?
>
> Because they are not needed.

Were they never needed or did something change?

2025-01-08 20:04 UTC, Elliria commented
> > * **CHANGELOG.rst**:
> >   ```
> >   * There are several versions of this file from the various commits in this PR, so I'm not sure which to review. As a result, I linked to the specific file used for any of the comments that have lines that no longer exist in the current diff so you can see exactly which lines I'm referencing.
> >   ```
> 
> I don't understand the issue. If you look at the diff for this file in GitHub it shows the difference between the original version that is currently in the branch and the changes that I am proposing be made to the file. Any interim versions that may have existed as the file was gradually reworked are no longer visible in the diff. .

Thanks for the explanation. I'm not able to keep up with the changes since this is so big that it takes time to go through it. My responses were not written in one session and are directed at the changes as they were at the time that I wrote them. It's also possible that some of what you're seeing is in response to individual commit comments. If you follow the links I provided for those ones, you'll find exactly what they refer to and can determine whether that's something that no longer applies or not.

2025-01-08 20:10 UTC, Elliria commented
@dlk3: 
> > * **CHANGELOG.rst**:
> >   * Are you planning on creating a separate issue for Debian like the [issue #998](https://github.com/autokey/autokey/issues/998) that you created for Ubuntu? If so, that would satisfy this TODO and it could be removed.
> > ```
> 
> No, Debian and Ubuntu are equivalent to me. If you'd rather have #998 reference Debian than Ubuntu, then please feel free to make that change. With #998 I simply wanted to make note of the things I saw when I created the installation process for Fedora. I thought doing that might make it a little easier for the person who has to do the same thing for Debian/Ubuntu know what issues they're facing.

Ah, I see. It's just that the Debian and Ubuntu parts of the code are in different places in the code-base and unless whoever works on it plans on doing both to close the issue, it might be better to split them up into separate issues. It's up to you.

2025-01-08 20:22 UTC, Elliria commented
@dlk3:
I figured I'd also do a round-up rather than responding individually to the ones below.

In response to this:

> If you disagree you are more than welcome to change anything I contribute to the project, that is your role as one of the owners of the project and its contents.

And this:

> I view this as the sort conflict issue that the developer who merges pull requests into the project code decides how to handle.

And this:

> I perceive a number of comments you've made in this review as concerning stylistic or level-of-detail issues in documentation. Rather than go back and forth on these, I think it is more efficient if you just edit the documents to suit your own preferences. It's my view that that's one of the rights and roles a project owner/administrator has, to take incoming contributions and shape them to be consistent with the project's standards. (I'll refer back to this response multiple times, below.)

And all of the ones below it that were like this:

> (Same response as above pertaining to stylistic or level-of detail issues.)

This is your PR. It wouldn't be right for me to interfere with your momentum by putting my hands all over your work. Go ahead and finish what you started in the way that you feel is best and we'll cheer you on from the sidelines. You're doing a great job helping out this project and we appreciate it.

2025-01-10 11:11 UTC, josephj11 commented
@Elliria I have several personal Gmail accounts and have never been asked to pay anything. Maybe commercial accounts do have to pay, but AutoKey as FOSS with no money changing hands at all and very small traffic usage ought not to be a problem. Several of us could share the user ID and password. Sounds good to me. Maybe autokey@gmail.com, if it's not taken. Your privacy concerns are valid. We just have to get our act together for sharing passwords. I dropped the ball on that one.

2025-01-13 21:42 UTC, Elliria commented
That sounds good, and we can work out the details in email.

2025-01-13 22:13 UTC, Technetium1 commented
Gmail isn't very friendly to account sharing, especially regarding future account recovery. [Bitwarden](https://bitwarden.com/) is a nice way to securely share credentials. Google is [deprecating](https://support.google.com/a/answer/14114704?hl=en) traditional IMAP auth, so you would need to use oauth, which would require 2 factor verification, meaning no 'easy' shared login.

The part of gmail that would cause an issue with payment is the storage size. If someone spams the address with large attachments, you must go to the web interface to manually empty the trash and reclaim the space, else wait 30 days for the trashed emails to actually delete. Each _free_ Google account gets 15GB combined storage for all account data. Depending on the retention desires that could be a problem. The cheapest upgrade is $3USD/mo for 200GB.

2025-01-14 00:59 UTC, josephj11 commented
@Technetium1 Good to know. If there is an easier option than using Gmail, that would be fine. It doesn't matter as long as it's free and easy.

2025-01-14 01:11 UTC, Technetium1 commented
@josephj11 [Riseup](https://riseup.net/en/email) and [Tuta](https://tuta.com/gmail-alternative) (formerly Tutanota) both have a solid history. Both only offer 1GB free and encourage clients to sync their mail locally using something like Thunderbird (which you should be doing anyway).

2025-01-14 01:43 UTC, josephj11 commented
@Technetium1 Thanks. Hadn't seen Riseup before. Looks quite impressive. Couldn't tell if it supports IMAP which we need for multiuser  access. Tuta doesn't support IMAP, so I don't see how that would work for us.

2025-01-14 16:01 UTC, Technetium1 commented
@josephj11 You're right! It is sad to see Tuta no longer supporting IMAP :disappointed: ... Reconfirmed that [Riseup still does](https://riseup.net/en/email/clients#choose-imap-or-pop). Sorry about that, wouldn't have recommended them otherwise.

2025-01-14 18:07 UTC, Elliria commented
If sharing security information about a Gmail account among several people is against Google's rules, then Gmail is out. Otherwise, instead of **Oauth2**, we could use an **app password**, which would be sharable the same way a regular password would be. Note that this will also only work if Google hasn't done away with the option to use an **app password** instead of **Oauth2**.

2025-01-14 18:49 UTC, Technetium1 commented
Setting an App password will work for IMAP, but be aware that 2factor **must** be maintained for app passwords to work: https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html / https://support.google.com/mail/answer/185833 ... I don't know if account sharing is explicitly against the terms of use for non-workspace users, but it does greatly increase the chance of an arbitrary account lock, especially if a random limit is hit: https://support.google.com/a/answer/33330?hl=en

You raise a good point about quota, Riseup does offer [situational quota increases](https://riseup.net/en/email/settings/quota), but it is not a given.

2025-01-15 09:34 UTC, josephj11 commented
Since this is primariy a way for someone who doesn't know about our GitHub and social media presence to establish initial contact with us, I expect the volume and storage requirements to be vanishingly small, so that shoudn't be an issue.

2025-01-15 22:04 UTC, Elliria commented
The way they discourage sharing for the app passwords is concerning. It's one step away from forbidding it, which they could decide to do. It looks like they don't currently outright forbid it, though. And other than any concerns about that, since volume and storage are unlikely to pose a problem, it looks like it could work, and as long as we each/all had full access to the account, maintaining the 2FA also shouldn't be a problem.

A private Google Group would have been perfect. With those, external users can **send** messages, but can't **read** messages, while internal members can do both. That, however, would require turning on **Groups for Business**. That, however, costs money, so it's out.

2025-01-19 16:37 UTC, mgclabs commented
Hi, big fan of AutoKey and noticed the email predicament.

Could you use the free gmail and set it to auto forward to your own email addresses or do you also need to reply from that email?

If so would Zoho Forever Free tier work?

https://www.zoho.com/mail/zohomail-pricing.html

2025-01-19 17:35 UTC, Technetium1 commented
@mgclabs unfortunately they are no longer a valid option after forcing payment for 3rd party client support: https://help.zoho.com/portal/en/community/topic/no-more-imap-pop-smtp-on-free-plans-even-on-referrals-with-no-notice

2025-01-19 19:10 UTC, mgclabs commented
@Technetium1 gotcha so IMAP access is a hard requirement

If plain old IMAP works Purelymail might be the cheapest, or using the activepieces free tier + gmail to create a homemade sort of ticket system with google sheets. Probably the best that can be done for free

2025-01-19 23:58 UTC, josephj11 commented
@mgclabs The only "hard" requirements are free and it must be easy for more than one of us to access it with read/write/admin permissions.  I would expect any new contact there to be (manually) redirected to one of our other community/support venues, so we shouldn't need any infrstructure such as a ticket system there.

2025-01-20 01:09 UTC, josephj11 commented
I asked Venice.ai about this:

Venice

3.18 sec

•

Llama 3.3 70B

You're looking for a way to manage contact information and authorship for your Python project on GitHub with multiple part-time developers. Here are some suggestions:

Shared Email Address: Create a shared email address using a free email provider like Gmail, Outlook, or ProtonMail. You can create a new account specifically for your project, and add all developers as owners or administrators. This way, everyone can access the email account and respond to messages.
GitHub Team Email: GitHub provides a feature called "Team" that allows you to create a shared email address for your team. You can add all developers to the team, and GitHub will generate a unique email address that forwards messages to all team members.
Mailgun or Sendinblue: These services offer free tiers that allow you to create a custom domain email address (e.g., [project-name]@your-project.org). You can add multiple users with full access to the email account.
Group Alias: Create a group alias using a service like Mailchimp or Google Groups. This allows you to create a single email address that forwards messages to all group members.
Open-Source Friendly Email Providers: Some email providers, like Riseup or Mailfence, offer free accounts specifically designed for open-source projects. These providers often have features like shared inboxes and collaborative filtering.


Tell me more about GitHub team email

GitHub Team Email is a feature that allows you to create a shared email address for your GitHub team. This email address can be used to receive notifications, messages, and other communications related to your GitHub project.

Here are some key features and benefits of GitHub Team Email:

Shared Email Address: GitHub generates a unique email address for your team, which can be used by all team members.
Email Forwarding: Emails sent to the team email address are forwarded to all team members, so everyone stays informed.
Customizable: You can customize the team email address to use a custom domain (e.g., [your-team]@your-domain.com) or a default GitHub-provided domain (e.g., [your-team]@github.com).
Access Control: Team owners and administrators can manage access to the team email account, adding or removing members as needed.
Notification Preferences: Team members can customize their notification preferences for the team email account, choosing which types of emails they receive.
To set up a GitHub Team Email, follow these steps:

Go to your GitHub repository or organization settings.
Click on "Teams" in the left-hand menu.
Create a new team or select an existing one.
Click on "Team settings" (gear icon).
Scroll down to "Email" and click on "Set up team email".
Choose your desired email address format (custom domain or default GitHub domain).
Configure notification preferences and access controls as needed.
Some use cases for GitHub Team Email include:

Project Contact: Use the team email address as a contact point for users, contributors, or customers.
Collaboration: Share the team email address with collaborators or partners working on your project.
Support: Use the team email address as a support channel for users reporting issues or requesting help.
Announcements: Send announcements or updates about your project to subscribers using the team email address.
Keep in mind that GitHub Team Email has some limitations:

Storage Limitations: Emails sent to the team email address are stored in Gmail's servers, subject to Gmail's storage limits (currently 15 GB per user).
Sending Limits: There are sending limits on emails sent from the team email address (currently 500 recipients per day).
SPF and DKIM Settings: You may need to configure SPF and DKIM settings for custom domains used with GitHub Team Email.
Overall, GitHub Team Email provides an easy-to-use shared inbox solution for teams collaborating on open-source projects hosted on GitHub!

The instructions are a bit off, but I could create a maintainers team and then figure out exactly what its email address is.
We have a colaborators team now, but that's a bit too broad.

2025-01-20 17:41 UTC, Technetium1 commented
I'm only aware of team notifications with Enterprise subscription or direct @ mentions of the org/team. I haven't checked in years, but I hope it's different now. I had a look around org settings for one I admin and was unable to find what is descibed by the AI. I even created a new team to test. If you could find where that is referenced in the docs I would love to have confirmation that it is possible!

2025-01-21 02:01 UTC, mgclabs commented
Might be a hallucination, o1 states:

"No. GitHub does not provide a built-in feature for team-wide email addresses or mail-forwarding the way this proposal describes. While GitHub organizations allow you to create “teams,” there is no GitHub-hosted mailbox or forwarding service that generates a “[team]@github.com” address and pushes mail out to all members. There is no “Team settings → Email” section in GitHub’s interface, nor a GitHub-supplied “team” email domain.

Here are the key points that show it is not a genuine GitHub feature:

• GitHub does not offer a team mailbox. Individual users can have “noreply” email forwarding for commits, but that is not a shared inbox.  
• You will not find any GitHub documentation or settings page describing how to set up a “GitHub team email.”  
• Storage and sending limits (like “500 recipients per day” or “15 GB limit”) referenced Gmail’s limits, but GitHub does not store emails or integrate with Gmail for a shared inbox.  
• There is no “@github.com” address you can register for a team. GitHub’s “@users.noreply.github.com” addresses are for commit attribution only, and these do not funnel to a shared mailbox."

Zoho may fit the bill a bit better in that case

A workable free approach for a shared team email in an open-source context usually involves something like: 

• Using a free Google Group or Microsoft Group for email distribution.  
• Setting up a dedicated mailbox on a free or low-cost domain host and creating forwarding/alias rules.  
• Using a contact page or form (e.g., in GitHub Pages) that routes to a common forwarding address.

If you need a single email contact for your team that distributes to everyone, you will need an external mailing list or a separate mail service; GitHub does not provide that functionality."

2025-01-21 06:43 UTC, josephj11 commented
@mgclabs Thanks for following up on this. So far I don't see an easy way to do this. The GitHub pages desnt work because they would already have an email address for the source code and we still don't have that address to use.

2025-01-22 21:56 UTC, Elliria commented
Unfortunately, [GitHub Team](https://github.com/pricing) isn't free.

2025-02-17 19:31 UTC, Elliria commented
## Call for Wayland testing:
We would appreciate additional testing of this pull request. To test it:
1. Create an Ubuntu 24.04 virtual machine in VirtualBox or your preferred virtualization program.
2. Open a terminal window.
3. Type or paste in these commands, one after another:
```bash
cd Desktop
git clone https://github.com/autokey/autokey.git
cd autokey
git fetch origin pull/992/head:pull_992
git checkout pull_992
python3 -m venv venv
source venv/bin/activate
pip install -r pip-requirements.txt
pip install packaging
cd lib
python3 -m autokey.gtkui -cl
# ... or...
python3 -m autokey.qtui -cl
```
4. Use AutoKey normally in as many ways as possible
5. Post the results in here.

Note that the default session for Ubuntu 24.04 is **Wayland**. It would be helpful if you also tested AutoKey in a **Xorg** session in Ubuntu 24.04 to see if there are any differences in behavior. To switch between the two session types and test AutoKey again:
1. Restart Ubuntu.
2. Go to the log-in screen.
3. Before you type in your password, click the gear icon in the bottom right corner of the screen and choose either **Ubuntu** for Wayland or **Ubuntu on Xorg**.
4. Open a terminal window.
5. Type or paste in these commands, one after another:
```bash
cd Desktop
cd autokey
source venv/bin/activate
cd lib
python3 -m autokey.gtkui -cl
# ... or...
python3 -m autokey.qtui -cl
```
6. Use AutoKey normally in as many ways as possible
7. Post the results in here.

2025-02-22 19:10 UTC, mgclabs commented
I would be happy to test, do y'all have a list of things we can try beyond our own personal workflow? Also, is using external python packages supported? I have never tried.

BTW not to hijack this issue but I pay for purelymail ($10/year) and would be happy to give y'all a purelymail IMAP account, it doesn't cost me any extra and happy to do it as long as autokey continues being developed since it is such a critical part of my toolbox (for example I have a shortcut called paste anyway where it skips system paste which is blocked sometimes and instead directly inputs which works even in web vnc sessions. Boom!).

You could use the purelymail domain for free or get one, either way.

2025-02-23 06:51 UTC, josephj11 commented
@mgclabs I'm open to trying purelymail as long as we have a way to gain/regain control of the account if you become unavailable and if more than one of us can admin it.

Other than the automated tests, we don't have a test suite and any attempt to start to build one would be appreciated.

Not sure what you mean by external packages. If you mean for automated testing, I have no idea. If you want to access them from within a script, things should work when called out to using methods from the subprocess or os modules, etc. If they try to grab keys, or do other things that AutoKey does internally or through its API, then you'll just have to experiment to see if any conflicts arise. (And be sure  to let us know what you find!) I have successfully used the yad GUI dialog manager from within an AutoKey script.

An important aspect of testing is to see what happens on different distros and different desktops... Doing that in VMs is time consuming and is better done by someone already familiar with their environment.

2025-02-23 23:33 UTC, Elliria commented
> I would be happy to test, do y'all have a list of things we can try beyond our own personal workflow?

I always test each default phrase and script. You can also try changing settings on phrases and scripts, adding abbreviations, setting hotkeys, choosing how AutoKey will interact with the target window, etc. And if you're feeling especially frisky, the AutoKey wiki contains a bunch of [example scripts](https://github.com/autokey/autokey/wiki/Example-Scripts) you can pick from for all sorts of things to try. Last, but not least, you can create some of your own phrases and scripts and feel free to share them in the wiki as well.

> Also, is using external python packages supported? I have never tried.

Yep. As an example this script imports the external **os** module, uses it to run a Bash command that runs the **test.py** Python script that's on the desktop, and displays its output in a dialog:
```python
# Import a module:
import os
# Store the path to a Python script in a variable:
my_script = "~/Desktop/test.py"
# Store the Bash command in a variable:
command = f"python3 {my_script}"
# Store the output of the Bash command in a variable:
output = system.exec_command(command, getOutput=True)
# Display the output in a dialog:
dialog.info_dialog(title="example", message=output, width="100")
```
 
> BTW not to hijack this issue but I pay for purelymail ($10/year) and would be happy to give y'all a purelymail IMAP account, it doesn't cost me any extra and happy to do it as long as autokey continues being developed since it is such a critical part of my toolbox (for example I have a shortcut called paste anyway where it skips system paste which is blocked sometimes and instead directly inputs which works even in web vnc sessions. Boom!).

That's a **very** kind offer ♥️, but it would be your email account even if you say it's okay for AutoKey to use it. It would probably be best for AutoKey to have its own email account.

2025-04-21 00:27 UTC, mgclabs commented
> > I would be happy to test, do y'all have a list of things we can try beyond our own personal workflow?
> 
> I always test each default phrase and script. You can also try changing settings on phrases and scripts, adding abbreviations, setting hotkeys, choosing how AutoKey will interact with the target window, etc. And if you're feeling especially frisky, the AutoKey wiki contains a bunch of [example scripts](https://github.com/autokey/autokey/wiki/Example-Scripts) you can pick from for all sorts of things to try. Last, but not least, you can create some of your own phrases and scripts and feel free to share them in the wiki as well.
> 
> > Also, is using external python packages supported? I have never tried.
> 
> Yep. See the [Modules - external](https://github.com/autokey/autokey/wiki/Modules#modules---external) section of the [Modules](https://github.com/autokey/autokey/wiki/Modules) AutoKey wiki page. Also, as an example that's in my collection of scripts, this script imports the external **os** module, uses it to run a Bash command that runs the **test.py** Python script that's on the desktop, and displays its output in a dialog:
> 
> ```python
> # Import a module:
> import os
> # Store the path to a Python script in a variable:
> my_script = "~/Desktop/test.py"
> # Store the Bash command in a variable:
> command = f"python3 {my_script}"
> # Store the output of the Bash command in a variable:
> output = system.exec_command(command, getOutput=True)
> # Display the output in a dialog:
> dialog.info_dialog(title="example", message=output, width="100")
> ```
> 
> > BTW not to hijack this issue but I pay for purelymail ($10/year) and would be happy to give y'all a purelymail IMAP account, it doesn't cost me any extra and happy to do it as long as autokey continues being developed since it is such a critical part of my toolbox (for example I have a shortcut called paste anyway where it skips system paste which is blocked sometimes and instead directly inputs which works even in web vnc sessions. Boom!).
> 
> That's a **very** kind offer ♥️, but it would be your email account even if you say it's okay for AutoKey to use it. It would probably be best for AutoKey to have its own email account.

All totally understandable, especially given my long response time! (Just got a new job yay!) but maybe i could throw the $10/year somewhere and the account would be 100% yalls. 

Btw i did try to run this in a live usb to test but ran into error after error and then got a new job, but i am doing a fresh install soon so hoping to test then.

2025-04-21 01:23 UTC, dlk3 commented
Oops, I didn't mean to click that!  Sorry @Elliria (I don't see any way to undo it either.)

2025-04-21 02:08 UTC, Elliria commented
Thank you for being willing to do testing, @mgclabs. That's always appreciated. There are updated instructions for testing this pull request in the [Call For Wayland Testing](https://github.com/autokey/autokey/discussions/1024) discussion.

And if you're feeling frisky, we could use testers to try out the updated instructions in the [Call For Hotfix Testing](https://github.com/autokey/autokey/discussions/1025) discussion for testing the hotfix that we need to move forward in development.

2025-04-21 02:32 UTC, Elliria commented
No worries, @dlk3. The same thing has happened to me, too, once upon a time.

[These instructions](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review) say that an administrator or a person with write-access to the repository can dismiss a review request, but I can only dismiss the review that I've already done. I don't have any power over yours. Maybe it will let you undo yours:
1. Open the pull request.
2. Make sure you're on the **Conversation** tab (it's the default tab).
3. Scroll down to the **Changes reviewed** section.
4. Click the **v** drop-down on the right.
5. Click the **...** drop-down on the right next to the review request you'd like to dismiss.
6. Click the **Dismiss review** option.

2025-05-25 00:36 UTC, mgclabs commented
Ok well I tried running again from new install of ubuntu 24.04 and ran into a few issues

[tests.txt](https://github.com/user-attachments/files/20428710/tests.txt)

I tried correcting on my own but hit a wall
[try_to_fix.txt](https://github.com/user-attachments/files/20428711/try_to_fix.txt)

2025-05-25 10:13 UTC, josephj11 commented
@mgclabs I only had a moment to scan all that output. The one thing that jumped out at me in several places were the repeated references to AutoKey 0.95.10 being installed. I may be wrong for this particuar type of testing, but the general practice is to backup your actions (under $HOME/.config/autokey/data by default), unintstall AutoKey 0.95.10 and install AutoKey 0.96.0 from our debs, make sure it works (under X11) and then proceed with further steps for testing new code for Wayland. I'm sure @dlk3 will have more clarity on all of this when he gets a chance to revievw it.

2025-05-25 12:41 UTC, Elliria commented
This may not solve it, but the one thing that stood out to me in the **tests.txt** file's output was the error complaining about **girepository-2.0** not being found. The ``libgirepository1.0-dev is already the newest version (1.80.1-1)`` output in the **try_to_fix.txt** file shows that you're using **girepository1.80**. Noble ships with the **libgirepository-2.0-0** package that should give it to you. If it doesn't, you could try installing the **libgirepository-2.0-dev** package.

2025-05-25 14:14 UTC, dlk3 commented
@mgclabs I'm not familiar with and have not I tested any of the "one-lined" install commands that have been floated in these threads.  I would recommend that installations be done following the instructions in the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) file.

It looks like Autokey is complaining that it cannot find the Gnome extension and that causes it to abend.  I can see in the middle of your <code>try_to_fix.txt</code> where you installed it.  Did you reboot after installing it and the udev rules file for uinput?  Did you enable the extension?  These are steps 3.3 and  3.4 in the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) instructions.

Regarding what @josephj11 said:  It doesn't matter whether or not there's another (production) version of AutoKey installed.  It isn't needed by the installation of the Wayland version of Autokey, but it shouldn't cause any harm by being there either.  (Assuming the prereq installation steps in the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) process have been completed.)

2025-05-25 22:23 UTC, josephj11 commented
@dlk3 I thought I might be wrong about that though it would make sure the dependencies were more up to date.

Programmers seem to have an obsession with fitting everything into one line of code. But it just makes the code impossibe to read and much harder to debug. When you do things a step at a time, you find the first error and don't have to deal with all the other ones that are artifacts of that error.

2025-07-04 20:18 UTC, mgclabs commented
Thanks ya'll and appreciate your patience.

> If it doesn't, you could try installing the **libgirepository-2.0-dev** package.

You are right it is installed already

> but the general practice is to backup your actions (under $HOME/.config/autokey/data by default), unintstall AutoKey 0.95.10 and install AutoKey 0.96.0 from our debs, make sure it works (under X11) and then proceed with further steps for testing new code for Wayland


> t looks like Autokey is complaining that it cannot find the Gnome extension and that causes it to abend. I can see in the middle of your `try_to_fix.txt` where you installed it. Did you reboot after installing it and the udev rules file for uinput? Did you enable the extension? These are steps 3.3 and 3.4 in the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) instructions.
> 
> Regarding what @josephj11 said: It doesn't matter whether or not there's another (production) version of AutoKey installed. It isn't needed by the installation of the Wayland version of Autokey, assuming the prereq installation steps in the [wayland_install.md](https://github.com/dlk3/autokey/blob/wayland/wayland_install.md) process have been completed. On the other hand it shouldn't cause any harm by being there either.

Yeah I thought I read to do that to get dependencies. In any case, following wayland_install.md is different than what I had read - and simpler.


I still hit an issue. Running ~/src/autokey/autokey-user-config
 errored out at the conditions ([[ and ]]) it said not found.
 
 Changing #/usr/bin/env sh
 
 to #!/bin/bash 
 
 fixed that
 
 After that, it said it needs me to fill in my keyboard and mouse details. Looks like I didn't have libinput installed, no big deal
 
 sudo apt install libinput-tools


Reboot and it still says it doesn't see my devices in the popup, but it is now listing them out in the terminal. After putting them in the config file, it loads!

So now I can actually test the program. Fingers crossed!

2025-07-05 07:44 UTC, josephj11 commented
@mgclabs Thanks for sticking with it! We look forward to your results.

One thing I'm curious about is what it will do with a phrase that includes Unicode characters and uses Paste using Keyboard. Probably still won't work, but  I can hope. :)

2025-07-05 20:31 UTC, dlk3 commented
@mgclabs Thanks for hanging in and making it all the way through.  You are definitely correct, the keyboard/mouse recognition code that's in there right now needs some work.  If the device doesn't have either "keyboard" or "mouse" as part of its name, then Autokey won't recognize it and it has be added to the config manually, as you did.

@josephj11 Wayland doesn't magically fix the unicode issue.  The only way I've gotten unicode to work is with a script.  And, if the output contains more than one unicode character, I have to put sleeps in between characters.

Example:  Here's a script I use to replace "1/2" with "¹⁄₂" as I type:

    keyboard.send_keys("<ctrl>+<shift>+u00b9 ")
    time.sleep(.05)
    keyboard.send_keys("<ctrl>+<shift>+u2044 ")
    time.sleep(.05)
    keyboard.send_keys("<ctrl>+<shift>+u2082")

2025-07-05 20:58 UTC, josephj11 commented
@dlk3 At least it's "half" fixed. LOL - the need for inter-character delays is bizarre. My type_slowly() function might help with that.

2025-07-26 23:19 UTC, mgclabs commented
Hmm I have a correction, I have a fresh install of Ubuntu 24.04 and libgirepository-2.0-dev was not installed, so last time I had it it must have come along when I was fiddling with dependencies.

I also did have to switch the script (~/src/autokey/autokey-user-config
) to /bin/bash again (making a note for myself in case i need to install from fresh again)

And also had to install 

sudo apt update
sudo apt install gir1.2-ayatanaappindicator3-0.1

Because I got this error "ValueError: Namespace AyatanaAppIndicator3 not available" when running "python3 -m autokey.gtkui -vc"

It didn't ask me to manually choose my keyboard and mouse this time, probably due to being on a laptop

2025-07-27 01:09 UTC, mgclabs commented
I tested a script (insert date time using keypress) and it worked but it seems to hijack the input in an odd way. For example it seems as soon as i used that datetime script by pressing the copilot key it would not let me left mouse click anything. I have attached the stdout. I did it again and same issue


[test.txt](https://github.com/user-attachments/files/21450719/test.txt)

2025-07-27 01:44 UTC, josephj11 commented
@mgclabs Thanks for the feedback!

This is the first trace I've seen from the new version. It's quite different than the old ones I'm used to.

What I did notice was

`2025-07-26 20:55:13,004 DEBUG - autokey.uinput_interface - Found device with mouse in the name, grabbing it: ELAN06FA:00 04F3:3293 Mouse
`
There isn't anything there about ungrabbing it, but IDK if there should be.

Sam, who did almost all of the work on this never talked with us about how it works. (To be fair, he asked us to test it and I'm not sure anyone did for quite a while.) He appears to be gone from GitHub since last September, so I don't  expect to hear from him.

Hopefully, one of our other members knowedgeable in Python can shed some light on what's going on here.

I can see what looks like your script running successfully several times, so that's good, but IDK any of the mechanics of how the new code works.

2025-07-28 04:23 UTC, Elliria commented
A few questions, @mgclabs:
* What are the contents of the script? Basically, what I'm getting at is that maybe the output of the script is waiting for input from you or throwing an error message in the background that isn't capture by AutoKey and you're not seeing it or interacting with it.
* Does the script work fine in the current version of AutoKey?
*  Is there anything else going on in the background at the same time while you're doing these tests?

2025-07-29 00:15 UTC, dlk3 commented
@mglabs - What you're seeing might be related to the hotkey you are using, not all of the key definitions are fully worked out in the code that Sam Sebastian provided.  I've bumped into similar problems here and there.  Can you try using a "simpler" hotkey to invoke your script and see if that changes anything?  I can't imagine any reason that the script itself would cause a problem like this and there's no indication of that in your log.

@josephj11 - The line you referenced about grabbing a mouse device is from code that Sam wrote and I modified that recognizes keyboard and mouse devices on the system when autokey first starts.   The "grabbing" being done here is the adding of the recognized device to the list of those that autokey will monitor for key events.

This line relates back to @mglabs' comment that they didn't have to manually configure their keyboard and mouse during this install on this laptop.  During startup  autokey recognized the laptop's keyboard and mouse because they have the words "keyboard" and "mouse" in their device names so these were "grabbed" automagically.

2025-07-29 05:07 UTC, josephj11 commented
@dlk3 So the mouse "grab" is normal and is not exclusive.

The problem with the hotkeys seems to be a genuine bug and needs an issue filed. IDK enough to provide all the needed details.

2026-02-09 14:29 UTC, dlk3 commented
This PR is seriously out of date so I am going to close it.  I have moved my changes into a fork of the AutoKey project, [AutoKey for Wayland](https://github.com/dlk3/autokey-wayland).  That fork is based off the "develop" branch of this project and I intend to maintain it such that it could be merged back in at will.

2026-02-09 14:29 UTC, closed without merging

2026-10-17 19:57 UTC, chrislee35 commented
Closing the loop on the open threads here, now that the PR is closed.

1. GPL on the GNOME extension: both `extension.js` files now carry `GPL-3.0-or-later`.
2. `imghdr` replacement: `highlevel.py` uses `python-magic`.
3. Logging the version: #1298 logs AutoKey's own version at startup and shutdown.
4. Mouse clicks stopping after a hotkey: I could not reproduce it on current develop (Ubuntu 24.04 Wayland, a `Ctrl+F8` hotkey and a `Meta+Shift+F9` chord, both still clicked normally afterward), so I am not filing an issue for it.
5. Still open: Unicode in "Paste using Keyboard" on Wayland (#1035, #29), the visgrep replacement (#470, #1001), and the shared project contact address in `common.py`.